pre_commit/util.py, tests/prefixed_command_runner_test.py
before:
```
$ python -m pre_commit.main install -f --install-hooks
pre-commit installed at /nail/home/buck/pg/2/.git/hooks/pre-commit
An unexpected error has occurred: CalledProcessError: Command: (u'virtualenv', u'/nail/home/buck/.pre-commit/repoSvhFNZ/py_env')
Return code: 1
Output: (u'Using real prefix \'/usr\'\nNew python executable in /nail/home/buck/.pre-commit/repoSvhFNZ/py_env/bin/python2.6\nAlso creating executable in /nail/home/buck/.pre-commit/repoSvhFNZ/py_env/bi
n/python\nInstalling setuptools, pip...\n  Complete output from command /nail/home/buck/.pre...py_env/bin/python2.6 -c "import sys, pip; sys...d\\"] + sys.argv[1:]))" setuptools pip:\n  \'import site\'
failed; use -v for traceback\nTraceback (most recent call last):\n  File "<string>", line 1, …
```
=> improve output in error case

pre_commit/clientlib/validate_config.py, pre_commit/clientlib/validate_manifest.py, testing/resources/arg_per_line_hooks_repo/hooks.yaml, tests/manifest_test.py, tests/repository_test.py
This allows (for instance) the `autopep8-wrapper` hook in https://github.com/pre-commit/pre-commit-hooks to default the `args` to `['-i']`
=> Default arguments from hooks.yaml

pre_commit/clientlib/validate_config.py, pre_commit/commands/run.py
This is an attempt to address #219.
As it is a first draft, it misses some tests and a bit of code cleaning, but I'd like an initial design review before fixing the final glitches.
**Example of valid _ .pre-commit-config.yaml_ using this feature :**
```
- local-hooks:
- id: no-todo
name: No TODO allowed in commited files
entry: grep -iI todo
expected_return_value: 1
language: system
files: ''
```
**Pros / Cons of the solution choosed:**
+ + end-user-friendly: the new "local-hooks" field schema is the same as _hooks.yaml_ schema
+ + nice reuse of MANIFEST_JSON_SCHEMA
+ + no more `_run_hook` / `_run_hooks` code duplication
+ + all the regressions tests pass
- - "local-hooks" and classical repo/sha/hooks objects are mixed together in _.pre-commit-config.yaml_
- - the `hooks_and_invokers` …
=> Preparatory work & clean-up for #219

pre_commit/commands/run.py, pre_commit/main.py, tests/commands/run_test.py
Change the behaviour for unstaged config per #157 discussion
- if allow unstaged config, puts a warning message that the config will still be stashed, but continues
- if not provided, errors out
stuff I'd expect we might want to change would be the actual content of the messages and perhaps what the "default" is here.  
thanks for the support! @asottile
=> --allow-unstaged-config arg

pre_commit/commands/autoupdate.py, testing/fixtures.py, tests/commands/autoupdate_test.py
I added a test, `test_autoupdate_local_hooks_with_out_of_date_repo`, that is currently failing without this patch.
The issue typically araise when mixing local & remote hooks : on a successful remote hooks autoupdate, local hooks are simply ignored when the new YAML config is writen to file.
=> Fixing bug with local hooks that disappeared during autoupdate

pre_commit/clientlib/validate_base.py
It would be nice if these binaries had a `--version` option as well as the `--help` option they already have.
They could use the same copy-pasted-from-stackoverflow snippet we use for the main pre-commit.
One benefit is that you can use help2man to generate man pages automatically for these validators.
(Normally these are only used as pre-commit hooks, but they can be used standalone as well. Debian wants manpages for any binaries, and we can generate them easily given `--help` and `--version`. The alternative is to not ship them with the Debian package, or to apply this patch only in the Debian package and not upstream.)
=> Add --version option to validator binaries

hooks.yaml, setup.py
This patch is needed for the Debian package. I'm not sure if you'll be interested in it upstream, but I think it's a reasonable change.
By having these entrypoints, we add the binaries `validate-config` and `validate-manifest` which are super-generic names. If a user installs pre-commit under their user or system-wide, they could end up with these confusingly-named binaries on their PATH.
I think it would be better to rename them to `pre-commit-validate-{config,manifest}` for a less ambiguous (and less generic) name. Since the primary use of these scripts is as a pre-commit hook, we can just change the entrypoint in `hooks.yaml` and won't break anybody's existing config.
The only thing this would break is if anyone is calling these scripts by hand, which seems unlikely.
=> Rename validate-{config,manifest} entrypoints

pre_commit/languages/ruby.py
A bit more details on this "Cygwin issue":
```
$ pre-commit run
[INFO] Installing environment for git://github.com/pre-commit/mirrors-puppet-lint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ['bash', '-c', '. /home/lucas_cimon/.pre-commit/repoiGcWZt/rbenv-default/bin/activate && cd /home/lucas_cimon/.pre-commit/repoiGcWZt/ && gem build *.gemspec && gem install *.gem']
Return code: 1
Output:
Successfully built RubyGem
Name: __fake_gem
Version: 0.0.0
File: __fake_gem-0.0.0.gem
Successfully installed __fake_gem-0.0.0
Errors:
WARNING:  licenses is empty, but is recommended.  Use a license abbreviation from:
http://opensource.org/licenses/alphabetical
WARNING: …
```
=> Adding "--no-document" argument to "gem install" command for ruby-based hooks to fix issue with Cygwin

pre_commit/languages/python.py, tests/repository_test.py
The main use case for this PR is to more easily work with user-local python installations, particularly pyenv's. This way a user can specify `~/.pyenv/versions/3.4.3/bin/python`. This is particularly useful when working with projects across many python versions, where it doesn't make sense to have them all available on your PATH, while still keeping the .pre-commit-config.yaml portable by not specifying an absolute path.
=> Allow specifying python version relative to user's home directory.

pre_commit/clientlib/validate_manifest.py, pre_commit/commands/install_uninstall.py, pre_commit/commands/run.py, pre_commit/main.py, pre_commit/resources/hook-tmpl, pre_commit/resources/pre-push-tmpl, tests/commands/run_test.py, tests/manifest_test.py
Solve #255
Allows hooks to be filtered to pre-commit or pre-push. The hooks section in .`pre-commit-config.yaml` can now have a `filter` key, which if defined, can be `pre-push` or `pre-commit`.
I have not written formal tests for this. If whoever is has control over this repo likes the effort, I will very happily add some unit tests and update documentation. Just to note that not only do I need this feature badly, but others (like #255) also need it.
=> Allow hooks to be applied to either pre-push or pre-commit

pre_commit/commands/install_uninstall.py, pre_commit/resources/hook-tmpl, pre_commit/resources/pre-push-tmpl, tests/commands/install_uninstall_test.py
There is a problem when pushing an empty changeset - the command `pre-commit --hook-stage push` will be run. But actually, if the changeset is empty, there is nothing to push (everything is up to date). So we should just exit.
=> Fix bug - pushing on an empty changeset

pre_commit/languages/ruby.py
Changed to use --no-ri --no-rdoc to fix gem installs on OS X
=> Changed to use --no-ri --no-rdoc

pre_commit/languages/pcre.py, testing/resources/pcre_hooks_repo/hooks.yaml, tests/repository_test.py
This allows to specify a list of args for pcre hook. I'd like to use pcre hook for multiline match, which can be achieved by adding a `-z` option to `grep`.
=> Allow args for pcre hook

testing/resources/pcre_hooks_repo/hooks.yaml, tests/repository_test.py
@tdeo @asottile 
This switches to a slightly different grep flag test since on some versions of grep I get an error:
grep: The -P and -z options cannot be combined
...which causes the tests to fail.
=> Use a different test for grep flags to support old grep

pre_commit/commands/run.py, testing/resources/modified_file_returns_zero_repo/bin/hook3.sh, testing/resources/modified_file_returns_zero_repo/hooks.yaml, tests/commands/run_test.py
For some linters such as eslint, there is no output on a successful --fix operation. This provides a basic message to the user which indicates that their hook failed due to a file modification.
Feel free to change the text to something better, but I wanted to keep it generic since perhaps some hooks may not be 'fixing' anything - ideally the text for eslint would say 'Files were fixed in this hook' or 'Fixing files...'. Another option here could be 'Modifying files...' to match similar text in hooks such as autopep8 (which uses the same style in 'Fixing ___').
=> Output a message when a hook fails due to file modification

pre_commit/output.py, setup.py
Hit https://github.com/chrippa/backports.shutil_get_terminal_size/issues/4 while implementing.  Should be fixed entirely by my PR there (and worked around by `or 80` in this PR)
=> Support terminal width on windows.  Resolves #199

pre_commit/commands/autoupdate.py
When running ```autoupdate``` with a hook in .pre-commit.yaml that does not exist in the current version of the repository there is an error: ```No handlers could be found for logger "pre_commit"```
Before:
```
$ pre-commit autoupdate
Updating git://github.com/pre-commit/pre-commit-hooks...already up to date.
Updating git://github.com/trbs/pre-commit-hooks-trbs.git...No handlers could be found for logger "pre_commit"
```
After:
```
pre-commit autoupdate
Updating git://github.com/pre-commit/pre-commit-hooks...already up to date.
Updating git://github.com/trbs/pre-commit-hooks-trbs.git...[ERROR] `flake8` is not present in repository git://github.com/trbs/pre-commit-hooks-trbs.git.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```
The error …
=> Set up logging handler in autoupdate

pre_commit/commands/run.py, tests/commands/run_test.py
Consider we have a branch A.
I create two branches B, C from A and make changes independently.
I merge changes from C into A.
Now if I run pre-commit between A and B, diff shows the changes from branch C also.
=> only consider forward diff in changed files

pre_commit/staged_files_only.py, tests/staged_files_only_test.py
=> Fix staged-files-only with a non-utf8-trailing-whitespace diff.  Resolves #397

pre_commit/staged_files_only.py
When git is configured to use an external diff tool to show diffs
(eg. 'git config diff.external mytool'), the stashing unstaged files
will create an empty file that can't be recovered.
Some modifications are permanently lost...
Just disable the ext-diff of git diff to avoid any issue.
(Question to pre-commit devs: why not using git stash directly ?)
=> Fix file stashing with external diff tool

pre_commit/commands/run.py, pre_commit/output.py, setup.py, tests/commands/run_test.py
This would factor out pyterminalsize and instead use 80 as a default width and expand if the hook names are long.
=> Use 80 or min width instead of terminal size

pre_commit/git.py, pre_commit/main.py
```
$ ../pre-commit/venv_windows_python/Scripts/pre-commit
[WARNING] pre-commit has detected a mix of cygwin python / git
This combination is not supported, it is likely you will receive an error later in the program.
Make sure to use cygwin git+python while using cygwin
These can be installed through the cygwin installer.
- python (windows)
- git (cygwin)
An unexpected error has occurred: WindowsError: [Error 3] The system cannot find the path specified: u'/tmp/empty'
Check the log at ~/.pre-commit/pre-commit.log
```
```
$ ../pre-commit/venv_cygwin_python/bin/pre-commit
Flake8...............................................(no files to check)Skipped
```
```
$ ../pre-commit/venv_cygwin_python/bin/pre-commit
[WARNING] pre-commit has detected a mix of cygwin python / git
This combination is …
```
=> Warn on cygwin python/git mismatch.  Resolves #354

tests/conftest.py
This broke running individual tests sometimes due to #434
=> Configure logging under test

pre_commit/main.py, pre_commit/runner.py, testing/fixtures.py, tests/commands/autoupdate_test.py, tests/commands/install_uninstall_test.py, tests/commands/run_test.py, tests/conftest.py, tests/runner_test.py
This PR is to add support for alternate config files as discussed in #432. I'm intentionally adding functionality  to the run and autoupdate commands and not install or uninstall as I imagine .pre-commit-config.yaml will always exist.
I think this may be all that's necessary for --config to work? If this approach looks good, I plan to add unit tests as well as run some manual smoke tests myself. Thought it would be prudent to sanity check these changes first, though.
Thanks!
=> Add option to run from alternate config file

.travis.yml, appveyor.yml, tests/commands/install_uninstall_test.py, tox.ini
Occurs when tests run with tox not with Travis CI or Appveyor
Changed existing tox setenv statement to use whitespace around `=` as per
http://tox.readthedocs.io/en/latest/example/basic.html#setting-environment-variables
Related to https://github.com/pre-commit/pre-commit-hooks/pull/154 and https://github.com/pre-commit/pre-commit-hooks/pull/155
=> Fix test error "fatal: empty ident name (for <(null)>) not allowed"

.travis.yml, CONTRIBUTING.md, pre_commit/languages/all.py, pre_commit/languages/docker.py, testing/resources/docker_hooks_repo/Dockerfile, testing/resources/docker_hooks_repo/hooks.yaml, testing/util.py, tests/languages/docker_test.py, tests/repository_test.py
This adds support for docker-based hooks.
Current expectations:
1. The hook should not be sad that we overwrite everything in /src by the cwd into it as a volume
2. entry in your hooks config is the cmd entrypoint inside the container
@asottile  see that same repo I sent you as an example.
Happy to add tests if we agree that this is sane
v2 might want this to clean up after itself.
=> Docker hook support for pre-commit

pre_commit/languages/docker.py, testing/resources/docker_hooks_repo/hooks.yaml, tests/repository_test.py
@asottile  here's a fix for entry args. lmk if there's some corner case that makes .split() not satisfactory
Also, seems optimal to not pass up the user. Couldn't get writes working on my localhost without. Docker will only set permissions to root if it's creating *new* files so... /shrug not sure! People could always pass it as an args? (Or maybe not if we don't expand env vars...). This has sort of always been the most annoying part of docker heh
=> Support docker hooks with args

pre_commit/commands/autoupdate.py, pre_commit/main.py, tests/commands/autoupdate_test.py
I had this great idea while bored on the train.  I wonder if it should be the default and instead there's a `--bleeding-edge` option.
=> Add a --tags-only option to autoupdate

pre_commit/repository.py, tests/repository_test.py
The approach that #480 takes to future-proof autoupdate a little more also improves the case for "hook not present yet".  We originally did some wordy work to suggest a way to upgrade for #386 in #387 but now that's not necessary \o/
CC @matkoniecz
=> Improve messaging for missing hook given #480

pre_commit/repository.py, tests/repository_test.py
I was investigating https://github.com/pre-commit/pre-commit-mirror-maker/issues/20 and realized running `gem install gem1:version1 gem2:version` can give different result from `gem install gem2:version2 gem1:version1`.
This PR keeps the list of additional dependencies of an hook in the order they appeared in the `.pre-commit-config.yaml`.
=> Keep dependency in order

pre_commit/parse_shebang.py
- The bare exe was the first filename attempted to match,
this change means it will be matched last, allowing other files
to be matched if they exist. The result is that eslint now works
on Windows.
- Possibly related to #200
=> Fix eslint on windows

pre_commit/resources/pre-push-tmpl
When pushing a branch that does not exist on the remote repository,
instead of blindly running the checks on every file, this commit locates
the first ancestor not present on the remote repository and uses its
parent as the source of the fileset calculation. If it has no parents,
then the remote repository has no common commits and the checks should
be run on all files.
=> Improve pre-push fileset for a new remote branch

pre_commit/commands/install_uninstall.py, pre_commit/main.py, pre_commit/resources/hook-tmpl, testing/fixtures.py, tests/commands/install_uninstall_test.py
When no '.pre-commit-config.yaml' file exists while `pre-commit` hooks
are enabled, `pre-commit` returns an error and the action is aborted.
This is a very common scenario when pre-commit is added later on a
project and the user wants to work on a previous branch where the
configuration file does not exist.
This commit checks whether a config file exists and runs only the legacy
pre-commit hooks (if any) when it is missing.
=> Do not run pre-commit if there is no config file

pre_commit/commands/install_uninstall.py, requirements-dev.txt, tests/commands/install_uninstall_test.py, tox.ini
I realized this wasn't necessarily rollback safe.  This makes it slightly more future-proof.
This feature really isn't used too much anyway (we usually run install with `--force`)
Perhaps the default behaviour of install should be changed as well?
=> Make hook-tmpl resilient to future changes

.coveragerc, pre_commit/color.py, pre_commit/color_windows.py
As of Windows 10, the Windows console supports (some) ANSI escape sequences, but it nees to be enabled using [`SetConsoleMode`](https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx) first.
If more extensive support is needed, or you want this to work on earlier versions of Windows, it would be probably be better to use a package like [colorama](https://pypi.python.org/pypi/colorama) instead, which automatically translates ANSI escape sequences to the equivalent Windows API calls. It also contains functions to format colored text.
This fixes #198.
=> Windows: enable ANSI escape support in console

pre_commit/clientlib.py, pre_commit/commands/run.py, pre_commit/output.py, testing/resources/logfile_repo/.pre-commit-hooks.yaml, testing/resources/logfile_repo/bin/hook.sh, tests/commands/run_test.py
Specify a filename on a per hook basis and
pre-commit will write the STDOUT and STDERR
of that hook into the file. Useful for CI.
Resolves #499.
=> Adds support for 'log_file' in hook config

pre_commit/clientlib.py, pre_commit/commands/run.py, tests/commands/run_test.py, tests/manifest_test.py
This option controls whether filenames are passed along as arguments to
the hook program.
=> Add pass_filenames hook option

testing/test_symlink, tests/git_test.py
On windows the "symlink" gets checked out as a normal file [breaking the hooks under test](https://ci.appveyor.com/project/asottile/pre-commit/build/1.0.1022/job/gf88t638f3aff1o9).
This moves the symlink to a test fixture instead
=> More specific symlink testing without checking in a symlink

pre_commit/languages/all.py, pre_commit/languages/docker.py, pre_commit/languages/golang.py, pre_commit/languages/helpers.py, pre_commit/languages/node.py, pre_commit/languages/pcre.py, pre_commit/languages/python.py, pre_commit/languages/ruby.py, pre_commit/languages/script.py, pre_commit/languages/swift.py, pre_commit/languages/system.py, pre_commit/manifest.py, tests/languages/all_test.py, tests/manifest_test.py, tests/repository_test.py
Resolves #365
Thoughts on this?
It has the potential to increase the number of virtualenvs when `language_version` is not specified in `.pre-commit-config.yaml` but at least they won't be defaulting to \~\*\~\*\~mysterious\~\*\~\*\~ undefined versions of python.
This should also remove the need to have `language_version` for python in most cases (as it'll now be properly inferred from the executable used to run pre-commit -- which is already [*kind of* the status quo](https://github.com/pre-commit/pre-commit/blob/853cbecd4e15aeb59e4730320dc90fe16afa219e/pre_commit/languages/python.py#L71-L74))
=> Use a more intelligent default language version

pre_commit/languages/python.py
With `v0.15`, I started getting the following bug when running `pre-commit install -f --install-hooks` on my Windows 10 machine:
```
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Users\\Evan\\.pre-commit\\repo8d84nqt_\\py_env-python3.6\\Scripts\\pip.exe', 'install', '.')
Return code: 1
Output: (none)
Errors: (none)
```
I managed to track the bug down to `virtualenv` not actually creating the `py_env-python3.6` directory, and from there to `virtualenv` not having been passed an actual executable on the `-p` option. The reason this was not happening was because `norm_version` was returning `version` instead of `find_executable(version)` when an executable was found. Thus, `find_executable` discovered that `version` had an executable, but then …
=> Fix windows virtualenv issue

pre_commit/languages/all.py, pre_commit/languages/docker.py, pre_commit/languages/golang.py, pre_commit/languages/helpers.py, pre_commit/languages/node.py, pre_commit/languages/pcre.py, pre_commit/languages/python.py, pre_commit/languages/ruby.py, pre_commit/languages/script.py, pre_commit/languages/swift.py, pre_commit/languages/system.py, pre_commit/repository.py, tests/languages/all_test.py, tests/languages/helpers_test.py, tests/repository_test.py
This will help with travis-ci caches
It's efficient to cache ~/.pre-commit in travis-ci as it makes hook execution fast the next run.  When travis-ci upgrades their system pythons this often causes failures due to libpython going missing
Here's a blurb of what this breakage looks like:
```
Trim Trailing Whitespace.................................................Failed
hookid: trailing-whitespace
/home/travis/.pre-commit/repoxffdwnip/py_env-python3.6/bin/python3.6: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```
I've only implemented `healthy` for python, the others can be written in the future.
=> Recover from invalid python virtualenvs

pre_commit/staged_files_only.py, tests/staged_files_only_test.py
Resolves #570 
I couldn't just use `autocrlf=false` invariantly -- it caused some other tests to fail!  I'm not terribly happy with this approach but I don't think there's an alternative.
I did create a [git mailing list entry](http://marc.info/?l=git&m=150161184929546&w=2) for this so maybe one day the git bug will be fixed
=> Workaround git apply with autocrlf=true bug

pre_commit/store.py
Some packages make use of git submodules, and require all of them to be in place to be installed. One example is my libtidy wrapper for node, which depends on the C sources for libtidy (unless a precompiled binary is available for a given platform). I've been asked to add pre-commit support in https://github.com/gagern/node-libtidy/issues/17 but testing that failed because the source tree was lacking its submodules.
=> Initialize git submodules

.pre-commit-config.yaml, .pre-commit-hooks.yaml
Not sure how this never dawned on me, but this hook is entirely useless as pre-commit already has to parse the entire configuration in order to run this hook 😆 
This was one of the first hooks before the entire idea was completely fleshed out so I guess it makes some sense.  Time to sunset this hook though 🌥
=> Remove validate_config hook

pre_commit/file_lock.py, pre_commit/repository.py, pre_commit/store.py, tests/commands/install_uninstall_test.py, tests/repository_test.py, tests/store_test.py
This attempts to solve #363
I've tested this on windows and linux and it appears to work as intended.  This adds some additional printing of `[INFO] Locking pre-commit directory` when cloning / installing repositories.
I used this script to test this somewhat-thoroughly:
```bash
#!/usr/bin/env bash
set -euxo pipefail
tmpdir="$(mktemp -d)"
cleanup() {
cat "$tmpdir/pre-commit.log" 2> /dev/null || true
rm -rf "$tmpdir"
}
trap cleanup EXIT
export PRE_COMMIT_HOME="$tmpdir"
seq 10 |
xargs -P10 --replace \
pre-commit run trailing-whitespace --files README.md
echo 'done!'
```
Would definitely love a second set of eyes on this and someone to verify that this approach also works on macos
=> Limit repository creation to one process

pre_commit/languages/all.py, pre_commit/languages/docker.py, pre_commit/languages/docker_image.py, pre_commit/languages/helpers.py, pre_commit/languages/pcre.py, pre_commit/languages/system.py, pre_commit/repository.py, testing/resources/docker_image_hooks_repo/.pre-commit-hooks.yaml, tests/repository_test.py
`docker_image` is intended to be a lightweight hook type similar to system /
script which allows one to use an existing docker image which provides a
hook.
Resolves #597
=> Add new docker_image language type.

pre_commit/error_handler.py, tests/error_handler_test.py, tests/main_test.py
I want to say this was originally here to work around the testing library at the time, but this seems to work just fine.
=> Use SystemExit instead of PreCommitSystemExit

pre_commit/resources/hook-tmpl
Independent of what hook type is running, the tool is always called `pre-commit`.
=> Fix error message during pre-push / commit-msg

.travis.yml, tests/git_test.py
Resolves #609
Seems there was only one test which actually depended on this configuration.
=> Remove --unshallow fetch from travis-ci config

.pre-commit-config.yaml, pre_commit/clientlib.py, pre_commit/commands/autoupdate.py, pre_commit/commands/migrate_config.py, pre_commit/commands/sample_config.py, pre_commit/main.py, pre_commit/runner.py, pre_commit/schema.py, testing/fixtures.py, tests/clientlib_test.py, tests/commands/autoupdate_test.py, tests/commands/migrate_config_test.py, tests/commands/run_test.py, tests/commands/sample_config_test.py, tests/main_test.py
This resolves #414
I've also added the following to aid in migration:
- `pre-commit migrate-config`
- attempts to intelligently upgrade the configuration to the new map format
- `pre-commit autoupdate` - by default calls `migrate_config(...)`
For now I have opted to _not_ issue a deprecation warning, I'll follow up with that in a later release.
=> Enable map configurations (config v2).

pre_commit/commands/autoupdate.py, pre_commit/commands/migrate_config.py, tests/commands/autoupdate_test.py, tests/commands/migrate_config_test.py
This fixes an unintentional regression in https://github.com/pre-commit/pre-commit/pull/610 introduced in 1.0.0
=> pre-commit migrate-config should not return nonzero when successful

pre_commit/resources/hook-tmpl
This also fixes a microbug (`pre-commit` not in path, custom `--config` during install) by combining the invocations together.
=> Use some bash best practices and simplify hook template

pre_commit/languages/golang.py, testing/fixtures.py, tests/languages/golang_test.py, tests/repository_test.py
This is necessary to show that `--depth` + the current approach to autoupdate do not mesh well: #628
This also fixes a microbug:
- `file://` clone paths for golang were being treated as urls
=> Use file:// protocol for cloning under test

pre_commit/commands/try_repo.py, pre_commit/git.py, pre_commit/main.py, pre_commit/manifest.py, pre_commit/repository.py, pre_commit/runner.py, testing/fixtures.py, testing/util.py, tests/commands/autoupdate_test.py, tests/commands/run_test.py, tests/commands/try_repo_test.py, tests/main_test.py, tests/make_archives_test.py, tests/manifest_test.py, tests/store_test.py
`try-repo` is useful for:
- Trying out a remote hook repository without needing to configure it.
- Testing a hook repository while developing it.
Refs #589
=> Add `pre-commit try-repo`

pre_commit/languages/docker.py
Without this, the hook fails on envs running with selinux enabled. This option automatically labels mounted volumes correctly.
=> Add selinux labelling option to docker_image hook type

pre_commit/commands/autoupdate.py, tests/commands/autoupdate_test.py
Aims to fix https://github.com/pre-commit/pre-commit/issues/660
=> [Fix] Add existing repo_config to output_repos

pre_commit/util.py
I do not necessarily like this idea -- this approach seems heavy handed compared to the simple problem it's trying to solve.
The change allows an entry in the pre-commit yaml config file, under a repo heading, which is a list of SSH environment variables to whitelist:
```
-   repo: git://server/my_private/pre-commit-hooks
sha: 616d91d4032cef3d742f85168387a4bfd66e2a05
git_env:
- GIT_SSH
- ...
hooks:
- ...
```
This change was needed because pre-commit clears GIT_* env vars when the repos are fetched via git binary in the subprocess call.
This is one way to solve for a very specific use case: A project builds but needs authenticated git access to a private repo holding hooks -- and the GIT_SSH env var is set to help facilitate. There are quite a lot of GIT_* env vars and while some of those …
=> Whitelists env var GIT_SSH

pre_commit/commands/run.py
On travis-ci which partially implements a tty so scripts spit out colors `git diff` will attempt to use a pager.
```
pyupgrade................................................................Passed
All changes made by hooks:
WARNING: terminal is not fully functional
-  (press RETURN)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something 
```
This forces `git` to not use a pager.
=> Invoke `git diff` without a pager

pre_commit/clientlib.py, pre_commit/commands/run.py, tests/commands/run_test.py, tests/repository_test.py
Relates to #689
It adds a `verbose` flag that can be set per hook and that allows stdout to be printed even when hook returned 0
=> Add a verbose hook option

pre_commit/commands/autoupdate.py, pre_commit/repository.py, pre_commit/store.py, tests/conftest.py, tests/repository_test.py
Resolves #590
There's one "questionable" change which is moving `CHAR(255)` => `TEXT` -- though in `sqlite` the width specifiers [are dropped](https://www.sqlite.org/datatype3.html#affinity_name_examples) so this is safe.
In addition to the regression test, I tested this manually:
```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
sha: v1.2.1
hooks:
-   id: flake8
additional_dependencies: [flake8-coding]
-   repo: https://github.com/pre-commit/pre-commit-hooks
sha: v1.2.1
hooks:
-   id: flake8
additional_dependencies: [flake8-quotes]
```
```console
$ pre-commit run --all-files
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing …
```
=> Each set of additional dependencies gets its own env

pre_commit/commands/autoupdate.py, pre_commit/main.py, tests/commands/autoupdate_test.py
=> Allow autoupdate --repo to be specified multiple times

.pre-commit-config.yaml, pre_commit/clientlib.py, pre_commit/commands/autoupdate.py, pre_commit/commands/migrate_config.py, pre_commit/commands/sample_config.py, pre_commit/commands/try_repo.py, pre_commit/git.py, pre_commit/main.py, pre_commit/repository.py, testing/fixtures.py, tests/clientlib_test.py, tests/commands/autoupdate_test.py, tests/commands/migrate_config_test.py, tests/commands/sample_config_test.py, tests/commands/try_repo_test.py, tests/make_archives_test.py, tests/repository_test.py, tests/staged_files_only_test.py, tests/store_test.py
Resolves #106 
The ticket mentions "ref", but I think "rev" is perhaps a better name?  Would love to get input here
This will be a slow migration, and during that time both `sha` and `rev` will be supported (but not both!)
I was able to leverage a [custom `cfgv` validator](https://github.com/asottile/cfgv#writing-your-own-validator) to accomplish this cleanly.
=> Migrate sha -> rev

pre_commit/languages/node.py
Makes a pretty big difference on size:
```console
$ nodeenv nenv3 --prebuilt --clean-src
* Install prebuilt node (9.7.0) ..... done.
$ du -hs nenv3/
70M	nenv3/
$ nodeenv nenv4 --prebuilt
* Install prebuilt node (9.7.0) ..... done.
$ du -hs nenv4
140M	nenv4
```
=> Use --clean-src for nodeenv

pre_commit/languages/pygrep.py, tests/languages/pygrep_test.py
As a follow-up on https://github.com/pre-commit/pre-commit/issues/634, I'm using today pcre hooks with `-z` option, which is the multiline mode, I'd like to add support for this to be able to move to pygrep hooks. I used the same argument name as `grep` does
=> Add multiline mode to pygrep

pre_commit/languages/golang.py
Here's the upstream issue: https://github.com/golang/go/issues/24360
=> Fix go 1.10: no pkg dir

latest-git.sh, pre_commit/commands/autoupdate.py, pre_commit/make_archives.py, pre_commit/store.py, testing/fixtures.py, tests/commands/autoupdate_test.py, tests/commands/install_uninstall_test.py, tests/conftest.py, tests/make_archives_test.py, tests/staged_files_only_test.py
Resolves #723
I manually verified the testsuite against git 1.8 (built from source) -- I don't think it's worth adding to the CI suite but that could be implemented as a followup.
When running the testsuite against 1.8 I also fixed ~3 tests in `tests/commands/install_uninstall_test.py` which are unrelated to the changes here (though in adjacent lines)
=> Restore git 1.8 support

pre_commit/store.py, tests/commands/try_repo_test.py
=> Fix regression: try-repo from relative path

pre_commit/commands/run.py, tests/commands/run_test.py
Apparently `mypy` will return different results depending on the ordering of files.  This makes that ordering more consistent.
=> Consistent ordering of filenames

pre_commit/commands/migrate_config.py
_technically_ yaml.load is unsafe, however the contents being loaded here are
previously loaded just above using a safe loader so this is not an abitrary
code vector.  Fixing it nonetheless :)
Thanks @tonybaloney!
=> Appease yaml.load linters

.travis.yml, testing/get-swift.sh
Added cache for Travis and Swift assets
=> Travis cache

testing/get-swift.sh
CC @expobrain
also switched from `shasum` to `sha256sum` since the former is part of `perl` and the latter is part of `coreutils`
=> Oops, this wrote a hash.txt file to the working dir

tox.ini
https://github.com/tox-dev/tox/pull/742 🎉
=> tox 3.1 passes PROCESSOR_ARCHITECTURE by default

pre_commit/commands/run.py, tests/commands/run_test.py
This branches fixes the run logic so that when
`pre-commit run some_hook -a` runs when the config contains
`stages: ['commit']` for some other hook, only the hook specified as an
argument will run.
Fixes #772
=> Run only the specified hook even when stages exist in config.

pre_commit/commands/autoupdate.py, pre_commit/commands/install_uninstall.py, pre_commit/git.py, pre_commit/repository.py, testing/fixtures.py, tests/commands/autoupdate_test.py, tests/commands/install_uninstall_test.py, tests/conftest.py, tests/error_handler_test.py, tests/languages/all_test.py, tests/make_archives_test.py, tests/repository_test.py, tests/staged_files_only_test.py
Fixes a lot of ResourceWarning like:
```python
pre_commit/repository.py:46: ResourceWarning: unclosed file <_io.TextIOWrapper name='~/.cache/pre-commit/repozvpv73iz/py_env-python3.6/.install_state_v1' mode='r' encoding='UTF-8'>
return json.loads(io.open(filename).read())
```
I also made changes to use the `with` context manager everywhere possible to prevent any other leaks.
=> Fix several ResourceWarning: unclosed file

pre_commit/color.py, tests/color_test.py
When running the command prompt on windows 8, color characters aren't supported.
This causes the pre-commit output to be really hard to read, as the color characters still get printed out.
Example of the current output:
```
(test_env) C:\Users\User\Desktop\pytest>pre-commit
←[43;30m[WARNING]←[0m Unstaged files detected.
[INFO]←[0m Stashing unstaged files to C:\Users\User/.cache\pre-commit\patch15356
78758.
black................................................(no files to check)←[46;30m
Skipped←[0m
blacken-docs.........................................(no files to check)←[46;30m
Skipped←[0m
Trim Trailing Whitespace.............................(no files to check)←[46;30m
Skipped←[0m
Fix End of Files.....................................(no files to check)←[46;30m
Skipped←[0m
Check …
```
=> Don't print bogus characters on windows terminals that don't support colors

pre_commit/meta_hooks/check_useless_excludes.py, tests/meta_hooks/check_useless_excludes_test.py
Fixes https://github.com/pre-commit/pre-commit/issues/704
=> Fix `check-useless-exclude` to consider types filter

pre_commit/prefix.py, pre_commit/repository.py, tests/repository_test.py
Thanks @chriskuehl for the report!
This was a regression introduced in b827694520be0f39bfc0599f3680b6c08b4516cf (first released in 1.7.0)
This speeds up installation of pre-commit/pre-commit-hooks from 90s to 5s
=> Install multi-hook repositories only once

pre_commit/xargs.py, requirements-dev.txt, tests/xargs_test.py
Changes how `xargs.partition` computes the command length (including arguments) depending on the plataform.
More specifically, 'win32' uses the amount of characters while posix system uses the byte count.
I'm splitting what was discussed in https://github.com/pre-commit/pre-commit/issues/691 in two parts (the next one implements upper limit length).
Since I have no resource to test this under windows, it might be good to ask for help from other developers/users to help validate the change.
=> Update xargs.partition with platform information

pre_commit/clientlib.py, pre_commit/languages/docker.py, pre_commit/languages/docker_image.py, pre_commit/languages/golang.py, pre_commit/languages/helpers.py, pre_commit/languages/node.py, pre_commit/languages/python.py, pre_commit/languages/ruby.py, pre_commit/languages/rust.py, pre_commit/languages/script.py, pre_commit/languages/swift.py, pre_commit/languages/system.py, pre_commit/xargs.py, setup.py, tests/languages/helpers_test.py, tests/repository_test.py, tests/xargs_test.py, tox.ini
Fixes #510
This implements something like the interface described in the ticket. Individual hooks have partitions run in parallel. The current logic is just a sketch (it uses the number of CPUs as the target concurrency, and does not adjust partitioning logic, so partitions are usually very large and the benefit is minimal).
Mainly looking for feedback on the current interface changes. I think it makes sense for `xargs()` to remain a "hook-ignorant" function (i.e. it's basically a generic Python implementation of xargs, and does not know anything about pre-commit or hook configs), so the logic for determining the target concurrency based on a hook's config lives in language helpers instead. This leads to a bit more boilerplate, but I could imagine different languages wanting to optimize …
=> Implement concurrent execution of individual hooks

pre_commit/languages/ruby.py
this will break old versions of `gem`, but without it it breaks new versions of gem 🤷‍♂️
=> Switch from deprecated docs-off args to --no-document

pre_commit/clientlib.py, pre_commit/commands/run.py, tests/commands/run_test.py, tests/repository_test.py
This is the least intrusive change.
We could consider using the alias in the output instead of the ID, but I'll defer any more directions on this PR through it's review comments.
=> Allow aliasing a hook and calling it by it's alias

pre_commit/main.py, tests/main_test.py
before this change, an error as follows would occur (I have `./pre-commit` and `./pre-commit-hooks` cloned side-by-side, I am inside the `./pre-commit/pre_commit` directory)
```
$ pre-commit try-repo ../../pre-commit-hooks/ trailing-whitespace
An unexpected error has occurred: CalledProcessError: Command: ('/usr/bin/git', 'ls-remote', '--exit-code', '../../pre-commit-hooks/', 'HEAD')
Return code: 128
Output: (none)
Errors: 
fatal: '../../pre-commit-hooks/' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```
After
```
$ pre-commit try-repo ../../pre-commit-hooks/ trailing-whitespace …
```
=> Fix try-repo relpath while in a sub-directory

pre_commit/languages/golang.py, tests/repository_test.py
If GOBIN is set, it will be used as the install path instead of the first item from GOPATH followed by "/bin".  If it is used, commands will not be isolated between different repos.
=> Ensure that GOBIN is unset when installing a golang hook

pre_commit/commands/migrate_config.py, tests/commands/migrate_config_test.py
Added if statement to migrate_config.py to prevent looping through header lines if configuration file is empty.
Resolves #929
=> Fix crash on `pre-commit migrate-config` when configuration is empty

pre_commit/git.py
This env may be required for git to work; unsetting it can cause clone, submodule commands, etc. to fail
occurs with bundled git, e.g. Fork or SmartGit git clients
This appears to be needed to fix #664, where setting GIT_EXEC_PATH is recommended. Fork rightly does this, however pre-commit is stripping GIT_EXEC_PATH, preventing it from fixing the issue even when it is set.
Logs:
```
[INFO] Initializing environment for https://github.com/asottile/reorder_python_imports.
An unexpected error has occurred: CalledProcessError: Command: ('/Applications/Fork.app/Contents/Resources/git-instance/libexec/git-core/git', 'submodule', 'update', '--init', '--recursive')
Return code: 1
Output: (none)
Errors:
/Applications/Fork.app/Contents/Resources/git-instance/libexec/git-core/gi …
```
=> don't unset GIT_EXEC_PATH

pre_commit/commands/try_repo.py, pre_commit/git.py, pre_commit/xargs.py, tests/commands/try_repo_test.py, tests/xargs_test.py
Fixes #953 
The issue occured in a following situation:
```
touch testfile
git add testfile
pre-commit try-repo .
```
Testfile is detected by `git diff HEAD` but ignored by `git add -u` so git saw no changes made and couldn't make a commit.
I'm all ears if there are other solutions. I tried stashing the changes but couldn't get it to work because refs were stored in different git directories. 'git add .' instead of 'git add -u' should solve it but it could add unwanted files for the try-repo run so I settled for what you can see here. Lemme know what you think :)
=> Fix try-repo for staged untracked changes

pre_commit/resources/hook-tmpl
This patch fixes an infinite process recursion when `.git/hooks/pre-commit.legacy` executes itself over and over. I don't know exactly how and why this `pre-commit.legacy` file was created but it is a copy of `.git/hooks/pre-commit`
=> Do not run legacy script again when this is the one being executed

pre_commit/commands/run.py, pre_commit/constants.py, pre_commit/main.py, pre_commit/resources/hook-tmpl, tests/commands/install_uninstall_test.py, tests/commands/run_test.py, tests/conftest.py, tests/repository_test.py
Adds a `prepare-commit-msg` hook stage which allows for hooks which add
dynamic suggested/placeholder text to commit messages that an author can
use as a starting point for writing a commit message.
An example being to pre-populate the first line of the commit message with some dynamic information such as the ticket ID and description (if branch name contains the ticket ID let's say). The benefit of this over a `commit-msg` hook in this scenario being that it doesn't modify an author's commit message 'behind their back'.
May help with #833 and relates to #884
=> Add support for prepare-commit-msg hooks

pre_commit/clientlib.py, tests/clientlib_test.py
=> Add warning to additional keys in config

pre_commit/resources/hook-tmpl
Resolves #1026
Test Plan:
- Stage a change
- Have an unstaged changed
- Run `git commit`
- `^C` while the commit is running
- Verify that the patch gets re-applied
_Ideally there isn't output spew, but that seemed unavoidable on windows_
=> Fix handling of SIGINT in hook script

tox.ini
to be able to set the dev environment as described in the [CONTRIBUTING.md](https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md#setting-up-an-environment)
=> restore testenv:venv section

azure-pipelines.yml, tests/repository_test.py
annoyingly it isn't on the linux agents yet -- apparently my repo will get that on 2019-06-04
I needed to add an additional variable to passenv for windows due to https://github.com/microsoft/azure-pipelines-image-generation/issues/988
=> azure pipelines now has rust by default on windows

pre_commit/store.py
I don't think this was actually succeeding before:
```console
$ bash -x t2.sh
+ set -euxo pipefail
+ git --version
git version 2.20.1 (Apple Git-117)
+ rm -rf repo1
+ git init repo1
Initialized empty Git repository in /private/tmp/x/repo1/.git/
+ cd repo1
+ git remote add origin https://github.com/asottile/pyupgrade
+ git -c protocol.version=2 fetch origin v1.20.1 --depth=1
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 38 (delta 4), reused 27 (delta 3), pack-reused 0
Unpacking objects: 100% (38/38), done.
From https://github.com/asottile/pyupgrade
* tag               v1.20.1    -> FETCH_HEAD
+ git checkout v1.20.1
error: pathspec 'v1.20.1' did not match any file(s) known to git
```
=> Fix shallow fetch by checking out FETCH_HEAD

pre_commit/commands/run.py, tests/commands/run_test.py
Adds the value of `hook-stage` to the error message for a missing hook id to suggest setting a different stage. 
Possible additions before merging:
- Add a prompt to set the hook-stage
- Add a search for the id in different stages to say `Did you mean to use --hook-stage bleh`
- Add tests for more than `commit` and `push`
=> Added hook-stage print to output for missing hook id

pre_commit/color.py, pre_commit/main.py, tests/color_test.py
This reverts all changes made by #1092 and replaces them by a change that simply overwrites the default value of the --color option with the value of the PRE_COMMIT_COLOR environment variable, if it is defined. As requested by @asottile in #1073.
=> Switch from NO_COLOR to PRE_COMMIT_COLOR environment variable

pre_commit/languages/docker.py, tests/languages/docker_test.py
Fixes #1072
Docker for Windows 
- mounts the volume passed via `-v` always using `root:root` as owner, even if a `-u UID:GID` option is passed
-  newly created files (e.g. via `touch`) also use `root:root` as owner, even if the container is run as non-root user
- read/write access is also provided to non-root users, even if `ls -l` yields `-rwxr-x-r-x`  as file permissions
- files created inside the container appear on the host as if they were created by the user running the docker command
This is because Docker for Windows currently implements host mounted volumes via SMB (see https://docs.docker.com/docker-for-windows/troubleshoot/#volumes), which handles the access to mounted files and does not allow changing permissions from inside the container (see docker/docker.github.io#3298). …
=> Fix docker based hooks failing on Windows

pre_commit/commands/init_templatedir.py, pre_commit/main.py, tests/commands/init_templatedir_test.py
- before this, it required a `git` repo to run, but it wasn't read at all
- before this, if the destination templatedir was at `.` and the setting was unset, pre-commit would not warn
- before this, pre-commit would not properly use `expanduser` like `git` does.  Resolves #1096
=> Several fixes for init-templatedir

pre_commit/languages/rust.py
cargo install now requires an additional `--path <TARGET>` argument.
Fixes #1112
=> rust language: use the new cargo install command

pre_commit/languages/python.py, tests/languages/python_test.py
For example, for sys.executable:
>   /usr/bin/python3 -> python3.7
...the default lookup may return either `python3` or `python3.7`. Make the order deterministic by iterating over tuple, not set, of candidates.
=> Stabilize python default version lookup

pre_commit/commands/init_templatedir.py, pre_commit/commands/install_uninstall.py, pre_commit/main.py, tests/commands/init_templatedir_test.py, tests/commands/install_uninstall_test.py, tests/commands/run_test.py
Resolves #1139
took this opportunity to also make `hook_types` required to make the api less pre-commit-hook-specific
=> Allow --hook-type to be specified multiple times

pre_commit/error_handler.py, tests/error_handler_test.py, tests/main_test.py
Added pre-commit version, `sys.version` and `sys.executable` after the stack traces in error messages. 
#1141
=> Add version information to error logs

pre_commit/parse_shebang.py, tests/parse_shebang_test.py
- Changed error message if executable is not executable
Closes:[1159](https://github.com/pre-commit/pre-commit/issues/1159)
=> Handle case when executable is not executable

pre_commit/languages/python.py, tests/languages/python_test.py
locally someone had `types/__init__.py` which caused the `healthy()` check to continually fail and recreate. this at least pushes the problem further down into hooks where an error message will give something googleable
=> Fix python.healthy() check with stdlib module clashes

pre_commit/main.py, tests/main_test.py
=> Show better error message when running inside `.git`

tests/parse_shebang_test.py
See #1235
This makes the test succeed better when not in a virtualenv (where both `python` and `python3` executables will exist)
=> Use echo instead of python in parse_shebang_test

azure-pipelines.yml, pre_commit/languages/all.py, pre_commit/languages/conda.py, pre_commit/resources/empty_template_environment.yml, pre_commit/store.py, testing/resources/conda_hooks_repo/.pre-commit-hooks.yaml, testing/resources/conda_hooks_repo/environment.yml, tests/repository_test.py
Fixes #1204
`.pre-commit-hooks.yaml`:
```
- id: black-conda
name: black-conda
description: "Black: The uncompromising Python code formatter"
entry: black
language: conda
require_serial: true
types: [python]
```
`environment.yml`:
```
channels:
- conda-forge
- defaults
dependencies:
- black=19.10b0
```
=> Support for conda as a language

pre_commit/color.py, pre_commit/commands/run.py, pre_commit/xargs.py, tests/commands/install_uninstall_test.py, tests/commands/run_test.py, tests/commands/try_repo_test.py, tests/repository_test.py, tests/xargs_test.py
Other side-effects of this change:
- the return code of an individual hook is shown
- the *maximum* return code is the one which is used (this should make it easier to debug for instance [this issue](https://github.com/pre-commit/pre-commit-hooks/issues/430))
(hard to tell here, but the old verbose changes the width of what gets rendered)
=> Make verbose output less special

pre_commit/git.py
=> Add GIT_SSL_CAINFO environment variable to whitelist.

pre_commit/git.py, tests/commands/try_repo_test.py
Resolves #1258 
it's not super useful to `try-repo path/to/bare/.git` but this makes it "work" -- the modified files thing doesn't function but that's fine
=> Allow try-repo to work on bare repositories

pre_commit/main.py
See issue #1273 
Fixes output when running `--version`.
Before
```bash
python -m pre_commit --version
__main__.py 1.20.0
```
After
```bash
python -m pre_commit --version
pre-commit 1.21.0
```
=> fix prog arg to return correct version

pre_commit/git.py
Can this change please get merged? We sit behind a proxy that messes with certificates...
=> exclude GIT_SSL_NO_VERIFY env variable from getting stripped

azure-pipelines.yml, pre_commit/languages/all.py, pre_commit/languages/perl.py, pre_commit/resources/empty_template_Makefile.PL, pre_commit/store.py, testing/gen-languages-all, testing/resources/perl_hooks_repo/.gitignore, testing/resources/perl_hooks_repo/.pre-commit-hooks.yaml, testing/resources/perl_hooks_repo/MANIFEST, testing/resources/perl_hooks_repo/Makefile.PL, testing/resources/perl_hooks_repo/bin/pre-commit-perl-hello, testing/resources/perl_hooks_repo/lib/PreCommitHello.pm, tests/repository_test.py
Here's a first cut for supporting Perl hooks. Appears to work for me with this .pre-commit-hooks.yaml locally added to a https://github.com/perltidy/perltidy clone + the usual config to use it elsewhere:
```yaml
- id: perltidy
name: perltidy
entry: perltidy --nostandard-output --backup-and-modify-in-place
language: perl
types: [perl]
```
No tests yet, haven't taken a look what it would take to add some. Throwing this here for comments already anyway.
=> Perl hook support

pre_commit/commands/run.py, tests/commands/run_test.py
If using the prepare-commit-msg and commit-msg stages specifically (such as with the try-repo command), the `--commit-msg-filename` arg must be provided.
Resolves #1336
=> Detect missing arg for prepare-commit-msg and commit-msg

pre_commit/commands/hook_impl.py, pre_commit/commands/run.py, pre_commit/constants.py, pre_commit/main.py, testing/util.py, tests/commands/hook_impl_test.py, tests/commands/install_uninstall_test.py, tests/commands/run_test.py, tests/repository_test.py
This adds support for the `post-checkout` hook.
Fixes: https://github.com/pre-commit/pre-commit/issues/1120
Documentation PR: https://github.com/pre-commit/pre-commit.github.io/pull/307
One thing I would still like to do, if possible, would be to force hooks like this to always have `always_run` be set since that is somewhat implied by the nature of the hook (since it doesn't operate on files).
=> Add post-checkout

.pre-commit-config.yaml, setup.cfg
[python 3 statement - 3.6.0](https://github.com/asottile/scratch/wiki/python-3-statement#360)
=> Drop python 3.6.0 support (broken NamedTuple)

pre_commit/error_handler.py, tests/error_handler_test.py
=> Don't crash on un-stringable exceptions

pre_commit/languages/python.py, tests/languages/python_test.py
=> mark a python environment as unhealthy if python goes missing

pre_commit/error_handler.py, pre_commit/util.py, tests/util_test.py
Resolves #1350
the output is a little non-ideal (repeated messages) but I can't think of a way to do this otherwise, looking at the shebang doesn't necessarily help (it could be an ELF binary, or a malformed ELF binary, or any other number of issues)
```console
$ pre-commit run wat --all-files
wat......................................................................Failed
- hook id: wat
- exit code: 1
[Errno 8] Exec format error: '/home/asottile/workspace/pre-commit/t.sh'
[Errno 8] Exec format error: '/home/asottile/workspace/pre-commit/t.sh'
```
=> Don't crash out on OSErrors in subprocess calls

pre_commit/languages/docker.py, tests/languages/docker_test.py
Previous PR https://github.com/pre-commit/pre-commit/pull/1094 hard code the docker user to `1000:1000` on Windows platform. This is a fragile assumption since not all docker image would have user 1000 configured inside of the container.
Instead, we don't use docker user on Windows to allow it to use the default user defined on the image.
=> Don't use --user when running docker on windows

pre_commit/commands/autoupdate.py, tests/commands/autoupdate_test.py
This PR aims to make pre-commit's `autoupdate` option preserve the line endings.
This is slight inconvenience when using windows but having all code use Unix type line endings.
=> Preserve line ending when running autoupdate

pre_commit/store.py
Empty local golang installs seem to fail when trying to use go modules in additional_dependencies. Test config:
```yaml
repos:
- repo: local
hooks:
- id: shfmt
name: shfmt
language: golang
additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt]
entry: shfmt
args: [-w]
types: [shell]
- id: misspell
name: misspell
language: golang
additional_dependencies: [github.com/client9/misspell/cmd/misspell]
entry: misspell
args: [-error]
types: [text]
```
misspell is there just to represent something that's not a go module, and to see this change didn't break it (it didn't).
With pre-commit 2.3.0 shfmt setup fails for me with golang 1.12, 1.13, and 1.14 with:
```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/go', 'get', 'mvdan.cc/sh/v3/cmd/shfmt')
return code: 1
expected …
```
=> Add dummy go.mod for local "empty" installs

pre_commit/commands/autoupdate.py, pre_commit/util.py, tests/commands/autoupdate_test.py
If `rev` is wrapped in single or double quotes (e.g. due to a yamllint quoted-strings rule), when
re-writing the `rev` to update it, honour the existing quotation style
Fixes #1434
=> Maintain scalar quoting style when autoupdate re-writes rev

pre_commit/languages/ruby.py
I was running into weird issues where pre-commit was trying to load gems installed by another ruby (yielding lots of warning about not pristine gems) than the local rbenv version, I tracked it down to the `GEM_PATH` environment variable, and this seems to fix it in my use-case
=> Unset GEM_PATH for ruby hooks

pre_commit/commands/run.py, pre_commit/meta_hooks/check_hooks_apply.py, pre_commit/meta_hooks/check_useless_excludes.py, tests/commands/run_test.py
=> normalize slashes even earlier on windows for filenames

pre_commit/git.py, tests/git_test.py
=> prevent infinite recursion of post-checkout on clone

CONTRIBUTING.md
There could still be missing dependencies, I'm not using a fresh environement
to test that. Also added the specific required git version see
https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.2.txt
=> Add three missing required dependencies in CONTRIBUTING.md

pre_commit/commands/init_templatedir.py, pre_commit/main.py, tests/commands/init_templatedir_test.py, tests/main_test.py
The hook template created by `pre-commit init-templatedir` acts like it was installed by `pre-commit install --allow-missing-config`. That behavior makes sense for most people: if you're working with some repos that have pre-commit and some that don't, it's annoying to uninstall pre-commit from the repos that don't use it. However, for people trying to adopt a policy of using pre-commit in every repo, it's easier to catch repos that are missing the config if pre-commit fails hard.
To support this special case, add a `--no-allow-missing-config` option to the `init-templatedir` command. When that option is set, create a template hook that fails in repos where the pre-commit config is missing.
=> Add --no-allow-missing-config option to init-templatedir

pre_commit/languages/python.py
this caused confusing error messages, and sometimes virtualenv can discover a better version than we can
=> remove hardcoded python location

pre_commit/languages/ruby.py
I used this gemrc to break things (default on opensuse):
```yaml
---
:benchmark: false
:install: --format-executable --no-user-install
install: --format-executable --no-user-install
:backtrace: true
:update_sources: true
:format_executable: true
:verbose: true
:update: --format-executable --no-user-install
update: --format-executable --no-user-install
:bulk_threshold: 1000
:sources:
- https://rubygems.org
```
=> Fix ruby hooks when --format-executable is in gemrc

pre_commit/languages/python.py, tests/languages/python_test.py
this was originally to work around a bug in old `virtualenv` -- since `virtualenv>=20` there's no more re-exec
=> don't pass through -p if using the default version

pre_commit/commands/sample_config.py, tests/commands/sample_config_test.py
This is a minor change. The sample config doesn't even have the latest major version in it.
[This](https://stackoverflow.com/a/12704727) provides the solution to what is proposed in the `TODO`.
The output from
```bash
git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags git://github.com/pre-commit/pre-commit-hooks '*.*.*' | tail --lines=1 | cut --delimiter='/' --fields=3
```
can be directly inserted inplace of the defined rev.
Alternatively one could borrow parts from the autoupdate command. The logic there seems to init a repository and then parses the output from git commands using functions from the util module. The above may or may not be overkill. I have not looked into the details of the different approaches yet. Seems doable though!
If that …
=> Update pre-commit version in sample config

.gitignore, pre_commit/languages/all.py, pre_commit/languages/dotnet.py, testing/gen-languages-all, testing/resources/dotnet_hooks_csproj_repo/.gitignore, testing/resources/dotnet_hooks_csproj_repo/.pre-commit-hooks.yaml, testing/resources/dotnet_hooks_csproj_repo/Program.cs, testing/resources/dotnet_hooks_csproj_repo/dotnet_hooks_csproj_repo.csproj, testing/resources/dotnet_hooks_sln_repo/.gitignore, testing/resources/dotnet_hooks_sln_repo/.pre-commit-hooks.yaml, testing/resources/dotnet_hooks_sln_repo/Program.cs, testing/resources/dotnet_hooks_sln_repo/dotnet_hooks_sln_repo.csproj, testing/resources/dotnet_hooks_sln_repo/dotnet_hooks_sln_repo.sln, tests/repository_test.py, tox.ini
Hello hello.
This PR adds [2nd class](https://github.com/pre-commit/pre-commit/blob/master/CONTRIBUTING.md#adding-support-for-a-new-hook-language) support for dotnet [tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create) by using `dotnet pack` and `dotnet tool install`.
I've also tested a "real world" hook:
<details>
```console
$ cd /tmp
$ rm -rf ./foo
$ dotnet new console --name foo
The template "Console Application" was created successfully.
Processing post-creation actions...
Running 'dotnet restore' on foo/foo.csproj...
Determining projects to restore...
Restored /tmp/foo/foo.csproj (in 190 ms).
Restore succeeded.
$ cd foo
$ git init
Initialized empty Git repository in /tmp/foo/.git/
$ sed -i 's/Console/    Console/g' Program.cs
$ pre-commit try-repo …
```
=> add initial dotnet support

tests/languages/pygrep_test.py
Sorry for raising a trivial PR - I just noticed there's a test where you have both
```
@pytest.mark.usefixtures('some_files')
```
and
```
def test_main(some_files
```
My understanding is that only of them is needed
=> Remove unnecessary fixtures in signatures from pygrep tests

pre_commit/languages/pygrep.py, tests/languages/pygrep_test.py
xref this comment on StackOverflow: https://stackoverflow.com/a/64344519/9988333
>  A PR may be considered if you can demonstrate a real use case for it
A use-case comes from `PyMC3`, where there is a pre-commit hook to check that all notebooks have a watermark. Currently, this is done by defining
```
- repo: local
hooks:
- id: watermark
name: Check notebooks have watermark
types: [jupyter]
entry: python scripts/check_watermark.py
language: python
```
in https://github.com/pymc-devs/pymc3/blob/master/.pre-commit-config.yaml, and then
```python
"""
Check that given Jupyter notebooks all contain a final watermark cell to facilite reproducibility.
This is intended to be used as a pre-commit hook, see `.pre-commit-config.yaml`.
You can run it manually with `pre-commit run watermark --all`. …
```
=> ENH add --negate flag to pygrep

azure-pipelines.yml, pre_commit/languages/all.py, pre_commit/languages/coursier.py, testing/gen-languages-all, testing/get-coursier.ps1, testing/get-coursier.sh, testing/resources/coursier_hooks_repo/.pre-commit-channel/echo-java.json, testing/resources/coursier_hooks_repo/.pre-commit-hooks.yaml, testing/util.py, tests/repository_test.py
This change adds coursier as a "language" to pre-commit with the goal of allowing the JVM ecosystem tooling to be used in pre-commit hooks. 
[coursier](https://get-coursier.io/) is a tool for fetching, building and launching JVM applications directly from the command line. It also has some features for easily compiling these applications to native binaries via GraalVM so you don't have to pay the JVM startup cost for invoking CLI tooling.
The big motivation for me making this change was to be able to use `scalafmt` and `scalafix` via pre-commit. I created a [mirror hook-repo of scalafmt](https://github.com/JosephMoniz/scalafmt/commit/4698aa2604e8b2ca8ebf97a9aafc5b1ef877f355) in order to test this change out.
This repo is usable via the following pre-commit config:
```yaml
repos:
- repo: …
```
=> add coursier (jvm) as a language

pre_commit/error_handler.py, tests/error_handler_test.py
This PR attempts to follow the Linux/Bash convention for exit codes. See more at [Exit Codes With Special Meanings](https://tldp.org/LDP/abs/html/exitcodes.html) (You might need to use the [Google web cache](https://www.google.com/search?q=%22Exit+Codes+With+Special+Meanings%22&oq=%22Exit+Codes+With+Special+Meanings%22), because the resource seems to be down right now).
Basically we will have the following:
- `1` for standard error
- `130` for interrupted process by user
- `3` for any unexpected error
Bash/GNU examples which return exit code `130`:
```bash
tail -f /dev/null
echo $?
sleep 42
echo $?
```
=> Distinct exit codes for the various error cases

pre_commit/languages/dotnet.py
From testing, I found that the `bin` and `obj` directories may be elsewhere depending on the particular hook project layout. I'd also like to cleanup the build directory properly, since we only need the `dotnetenv-default` dir after we install the tool.
This patch should solve both cases.
=> fix dotnet build cleanup

pre_commit/commands/autoupdate.py
this wasn't needed after we were parsing newlines directly
=> remove DOTALL on REV_LINE_RE

pre_commit/commands/run.py, pre_commit/git.py
When git status runs in a repo with submodules, it'll recursively run
git status in every submodule as well by default (sequentially).
git status is substantially slower on Windows than on Linux. git diff
behaves similarly to git status in terms of running recursively within
all submodules. In repos with hundreds of submodules, this quickly adds
up when git status/diff are called multiple times. Pre-commit runs
git status once at the beginning of an operation and then runs git diff
before and after each hook. These calls quickly add up and make
pre-commit unusable in large repos with lots of submodules.
This commit drastically improves performance in repos with lots of
submodules and fixes #1701 by telling git status and git diff to ignore
submodules. This change is not expected to have …
=> Improve performance by ignoring submodules

pre_commit/clientlib.py, tests/clientlib_test.py
=> added warning if globs are used instead of regex

pre_commit/languages/python.py, tests/languages/python_test.py
=> fix for base executable with non-ascii characters on windows

pre_commit/git.py
Resolves #1720
The cygwin check depends on being in a git repo, but not all of the pre-commit commands need a git repo (such as `gc` / `clean` / `init-templatedir`) -- allow the cygwin check to fail silently here
=> don't crash on cygwin mismatch check

pre_commit/util.py
Writing a test for this one is tricky, because I was seeing the issue
only when the directory being removed is a docker volume, so instead of
getting EACCES we get EPERM.
This is easy to reproduce though. The existing test fails when the
directory being used for the files is a docker volume:
```
% docker run \
-v $(mktemp -d):/tmp \
-v ${PWD}:/src \
-w /src \
python:3 \
bash -c 'pip install -e . && pip install -r requirements-dev.txt && python -m pytest tests/util_test.py'
```
=> util: also run chmod on EPERM

pre_commit/clientlib.py, tests/clientlib_test.py
resolves #974
- only added a warning instead of raising an error because this might break multiple projects otherwise
- not sure if other mutable revs should also cause a warning, couldn't think of a way to detect them in general …
- the check could also be included in the `MigrateShaToRev`-class, but i think it's better to keep them separated
- test only checks for `HEAD`, this is sufficient imo, but i can also change it so it tests for all mutable revs defined in `{'HEAD', 'stable', 'master'}`
=> added warning if mutable rev is used

pre_commit/clientlib.py, tests/clientlib_test.py
extends #1702 (see [this](https://github.com/pre-commit/pre-commit/pull/1707#issuecomment-753351851) comment).
i used the same validator. to distinguish between a hook field and a top-level field i checked if `id` is present in the dictionary. i think this should be fine, but if you have a better idea just let me know :)
=> extended warning if globs are used instead of regex to top level

tests/repository_test.py
this was broken recently when that moved to go modules: https://github.com/golang/example/commit/bcf50bfd7dcd8020c90965747d857ae42802e0c5#commitcomment-46255173
=> fix reference to github.com/golang/example

pre_commit/languages/golang.py, tests/repository_test.py
resolves #1788 
note that i also added `depth=1` to reduce cache size and installation time. not sure if the whole command call should be replaced with `_shallow_clone`, depends on whether you want to keep all command calls within the helper module or not.
=> added recursive repository support for golang

pre_commit/clientlib.py, tests/clientlib_test.py
Instruct users how to prevent a mutable rev in repo warning.
=> Instruct users how to prevent a warning.

pre_commit/git.py, tests/main_test.py
=> Fix pre-commit install on subst drives

pre_commit/resources/empty_template_go.mod, testing/resources/golang_hooks_repo/go.mod
Go 1.16 changes the way modules are handled. It now expects Go projects to have non-empty `go.mod` files.
This change is compatible with Go 1.15.
Fixes #1815
---
The golang tests pass under all combinations of `Go [1.15|1.16]` + `GO111MODULE=[""|"on"|"auto"]`.
I could also install and run the following hook successfully with both Go 1.15 and Go 1.16:
```
- repo: local
hooks:
- id: shfmt
name: Format shell files with shfmt
language: golang
additional_dependencies: ["mvdan.cc/sh/v3/cmd/shfmt@v3.2.1"]
types: [shell]
entry: shfmt -w
```
These changes work for my use cases, and they seem sensible to me, but I'm not all that familiar with Go modules, so perhaps this has some implications I don't know about.
=> Add support for Go 1.16

pre_commit/commands/hook_impl.py, pre_commit/commands/run.py, pre_commit/constants.py, pre_commit/main.py, testing/util.py, tests/commands/hook_impl_test.py, tests/commands/install_uninstall_test.py, tests/commands/run_test.py, tests/repository_test.py
- Add: post-merge hook support
- Add post-merge tests
See commit message.
=> Add support for post-merge hooks

azure-pipelines.yml, pre_commit/languages/all.py, pre_commit/languages/r.py, pre_commit/resources/empty_template_renv.lock, pre_commit/store.py, testing/gen-languages-all, testing/get-r.ps1, testing/get-r.sh, testing/resources/r_hooks_repo/.pre-commit-hooks.yaml, testing/resources/r_hooks_repo/DESCRIPTION, testing/resources/r_hooks_repo/additional-deps.R, testing/resources/r_hooks_repo/hello-world.R, testing/resources/r_hooks_repo/renv.lock, tests/languages/r_test.py, tests/repository_test.py
This PR aims to add 2nd level support for R to pre-commit via the virtual environment manager [renv](https://rstudio.github.io/renv/), motivated by isolated dependency management and (hopefully) compatibility with pre-commit.ci for 2nd level languages as outlined in https://github.com/lorenzwalthert/precommit/issues/215. The implementation follows the recently contributed support for conda (#1232) for source code and tests as well as the implementation of the python virtualenv language.
Further considerations:
* ~Initial tests only run on Linux. I have to add other platforms as we go if this PR is generally approved.~
* ~I'd appreciate feedback to the questions in the source code comments, in particular on whether or not to remove `in_env()` as it seems not needed or whether it should be …
=> Support for R / renv as a language

pre_commit/xargs.py
resolves pre-commit/mirrors-prettier#7
=> give xargs batch file execution additional headroom

pre_commit/languages/docker.py, tests/languages/docker_test.py
Currently pre-commit mounts the current directory to /src and uses
current directory name as mount base.
However this does not work when pre-commit is run inside the container
on some mounted path already, because mount points are relative to the
host, not to the container.
Fixes #1387
Second try. Sorry, no way I can not copy-paste `in_docker` one, it looks too straightforward and quite pythonic already IMO. But the rest was indeed not really optimal, rewrote completely.
=> fix: fix path mounting when running in Docker

pre_commit/languages/r.py
This changes the criteria for determining if a hook repo is an R package: I suggest to check for `Package:` in `DESCRIPTION` (like {devtools}) to determine if a repo is an R package, we previously checked on the less commonly used `Type: Package` field. The definition matters because non-package repos are not installed.
I’ll send a PR to update the docs if it goes through.
=> Use more common package definition for R

pre_commit/languages/r.py, pre_commit/resources/empty_template_LICENSE.renv, pre_commit/resources/empty_template_activate.R, pre_commit/store.py, testing/resources/r_hooks_repo/renv/LICENSE, testing/resources/r_hooks_repo/renv/activate.R, tests/store_test.py
Attempts to solve #1835 as initially outlined in https://github.com/pre-commit/pre-commit/issues/1835#issue-826659015. To further avoid warnings for differing R versions, we suppress warning messages on environment loading. To not write infrastructure like `.Rprofile`, we use `renv::load()` over `renv::activate()`. For installing additional dependencies, we also added skipping of the startup process. I think after #1878, I might have fixed the biggest bugs I created -.-
=> Avoid warnings with R hooks when renv version don't match

pre_commit/languages/r.py, tests/languages/r_test.py
The `entry` for r hooks is very similar to `language: script` (in the case a path is supplied):
```yaml
-   repo: local
hooks:
-   id: consistent-release-tag
name: consistent-release-tag
entry: Rscript inst/consistent-release-tag
language: r
```
For local hooks, we don't need to prefix the path (which currently happens). This PR fixes this if `scr` of the `hook` is local.
=> R local hooks should not prefix hook path

pre_commit/commands/install_uninstall.py, tests/commands/install_uninstall_test.py
=> read legacy hooks in an encoding-agnostic way

pre_commit/languages/docker.py, tests/languages/docker_test.py
The hostname is not always the container id. Get the container id from
/proc/1/cgroup. Fixes #1918.
=> A more reliable way to get the container id.

pre_commit/git.py, tests/git_test.py
=> fall back to full diff on disparate histories

pre_commit/clientlib.py, tests/clientlib_test.py
originally reported in https://github.com/pre-commit-ci/issues/issues/84
=> make `repo: meta` only apply to top level configuration

pre_commit/meta_hooks/check_useless_excludes.py, tests/meta_hooks/check_useless_excludes_test.py
=> fix check-useless-excludes for exclude of broken symlink

pre_commit/commands/migrate_config.py, tests/commands/migrate_config_test.py
=> remove duplicate warnings while running autoupdate

pre_commit/commands/hook_impl.py, pre_commit/commands/run.py, pre_commit/constants.py, pre_commit/main.py, testing/util.py, tests/commands/hook_impl_test.py, tests/commands/install_uninstall_test.py, tests/commands/run_test.py, tests/repository_test.py
=> Add: post-rewrite hook support

pre_commit/clientlib.py, tests/clientlib_test.py
Add warning about unnecessary slash regex as per #2043
=> Add warning for regular expression with [\/] (#2043)

pre_commit/staged_files_only.py, tests/staged_files_only_test.py
=> make sure to not discard changes even if submodule.recurse=1

tests/repository_test.py
this is just to unbreak CI -- probably not the best solution
=> bump perltidy version

pre_commit/git.py, tests/git_test.py
Add exceptions to the git env so externally configured gitconfig
values set via `GIT_CONFIG_KEY_<n>`, `GIT_CONFIG_VALUE_<n>` and
`GIT_CONFIG_COUNT` get passed through. This is e.g. useful when using
the env to inject insteadOf configurations to force use of proxy servers
in a CI environment.
=> support gitconfig from env

pre_commit/clientlib.py, tests/clientlib_test.py
test: Test case parameters for said regular expression
refactor: For-loop for regex warnings instead of multiple if statements
resolves #2151
=> fix: Add missing warning for regular expression with [\\/]

pre_commit/languages/golang.py
`go install` is the recommended way to install modules starting from go 1.16.
In go 1.18 `go get` cannot be used anymore to install packages [1]. go 1.18 is
not released yet.
[1] https://tip.golang.org/doc/go1.18#go-command
=> Use 'go install' instead of 'go get'

pre_commit/languages/r.py
Hooks with `language: r` fail [under certain circumstances](https://github.com/lorenzwalthert/precommit/issues/342) if there is a virtual R environment present in the repo where a user want's to use hooks. This is because the env variable `RENV_PROJECT` is set in the terminal by some editors, e.g. RStudio to the virtual R environment of the user, but when pre-commit installs hooks (from that IDE terminal), it should not use that environment (obviously). Hence, we should unset that env variable before installing hooks. See https://github.com/rstudio/renv/issues/900 for an in-depth discussion.
In addition, the command line executable `Rscript` should not be used when called from R itself for some [version incompatibility](https://stat.ethz.ch/pipermail/r-devel/2018-February/075507.html), …
=> Make `language: r` work when there is already a renv in the working directory and `RENV_PROJECT` is set

pre_commit/clientlib.py, tests/clientlib_test.py
would have avoided some confusion in #2180
=> forbid overriding `entry` for meta hooks

pre_commit/commands/install_uninstall.py, requirements-dev.txt
=> always use #!/bin/sh on windows

pre_commit/languages/conda.py, tests/languages/conda_test.py
=> Add mamba support to `language: conda`

pre_commit/main.py
This PR fixes two minor typos where the help for `--from-ref` and `--to-ref` referred to the same command instead of the paired command.
=> Fix typo in help docs for to-ref and from-ref

pre_commit/languages/r.py
This fixes the windows build for this repo.
Fixes the failing R build as discussed in https://github.com/pre-commit/pre-commit/pull/2272#issuecomment-1059656551 by never installing R packages from source. This may create problems if no binary is available for a platform, as the common CRAN mirrors only provide binaries for macOS, Windows and popular Linux distributions. 
If that's a problem, my PR could be altered to try a source installations after a binary installation failed, with some additional complexity that can't be easily tested in the R code that is provided as string here. I am not sure what platforms are officially supported here.
=> Avoid build-time dependencies by prioritising binary over source dependencies for R

pre_commit/commands/autoupdate.py, pre_commit/git.py, tests/commands/autoupdate_test.py
This PR uses `git tag --points-at` to check if multiple tags exist for a given tag. If so, it tries to pick the "best" one that looks like a version tag.
Fixes #2311
=> Pick a tag if multiple tags exist on a SHA.

pre_commit/commands/install_uninstall.py, pre_commit/git.py, tests/git_test.py
The issue happens because `get_git_dir()` returns `git rev-parse --git-common-dir` and not `git rev-parse --git-dir` as expected. This PR introduces `get_git_common_dir()` and uses it where the common dir is required and the local .git dir of the current working copy in all other cases.   
This fixes https://github.com/pre-commit/pre-commit/issues/1972, false positives in case of worktrees. 
This PR is in the draft state to debug CI issues.
=> Use the correct .git path in case of worktrees. 

pre_commit/clientlib.py, pre_commit/commands/init_templatedir.py, pre_commit/commands/install_uninstall.py, pre_commit/constants.py, pre_commit/main.py, tests/commands/install_uninstall_test.py, tests/main_test.py
this implements a configurable fallback for the default value of `pre-commit install`
(this feature is kinda broken by design, but maybe this will stop people asking for it)
=> implement default_install_hook_types

testing/resources/golang_hooks_repo/go.mod, testing/resources/golang_hooks_repo/go.sum, tests/repository_test.py
annoyingly it looks like `go.sum` is now required as is a fully filled out `go.mod`
=> fix tests for golang 1.18

pre_commit/commands/hook_impl.py, tests/commands/hook_impl_test.py
From the `pre-push.sample` file:
> Information about the commits which are being pushed is supplied as
> lines to the standard input in the form:
>
>   `<local ref> <local sha1> <remote ref> <remote sha1>`
When `<local ref>` is not simply a branch name, but a more general
ref (see git-rev-parse(1)), it could contain whitespace, and that
breaks the split() call that expected only 3 spaces in the line.
Changed to use `rsplit(maxsplit=3)` since only the <local ref> is
likely to have embedded whitespace.
Added a new test case for the same.
Fixes #2344
=> pre-push: fix stdin line splitting when <local ref> has whitespace

.pre-commit-hooks.yaml, azure-pipelines.yml, pre_commit/clientlib.py, pre_commit/commands/validate_config.py, pre_commit/commands/validate_manifest.py, pre_commit/main.py, testing/get-swift.sh, tests/clientlib_test.py, tests/main_test.py, tests/repository_test.py
slightly improves tab complete for `pre-<tab>`
=> deprecate pre-commit-validate-{config,manifest}

pre_commit/languages/ruby.py, tests/repository_test.py
When `--user-install` is set in the gemrc config file, `gem` ignores
`GEM_HOME`. `--no-user-install` prevents this behaviour.
Resolves #2383
=> Force gem installation into `GEM_HOME`

pre_commit/util.py
Use the child instead of parent fd when manipulating pty for color.
Fixes https://github.com/pre-commit/pre-commit/issues/2389
=> Switch pty use to fix solaris

testing/fixtures.py
Fixes https://github.com/pre-commit/pre-commit/issues/2391
More modern git versions have the ability to set the default branch name, and recent documentation warns against expecting the branch name to be stable. As such, added an explicit set to  `master` (as that was the minimal change and is backwards compatible with older versions of git.
Call is made in a try/except block checking for errors and stepping back to the previous version without initial-branch
=> force default branch name for tests

pre_commit/main.py
diff from the help:
```diff
diff --git a/before/_base b/after/_base
index d11959d..d8519ec 100644
--- a/before/_base
+++ b/after/_base
@@ -1,9 +1,9 @@
usage: pre-commit [-h] [-V]
-                  {autoupdate,clean,hook-impl,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,validate-config,validate-manifest,help}
+                  {autoupdate,clean,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,validate-config,validate-manifest,help,hook-impl}
...
positional arguments:
-  {autoupdate,clean,hook-impl,gc,init-templatedir,install,install-hooks,migrate-config,run,sample-config,try-repo,uninstall,validate-config,validate-manifest,help}
+  {autoupdate,clean,gc,init-templatedir,install,install-hooks,migra …
```
=> remove unused --config options from commands which don't use it

pre_commit/languages/helpers.py, pre_commit/parse_shebang.py
=> remove imports from TYPE_CHECKING (py37+)

tests/error_handler_test.py
Fixes https://github.com/pre-commit/pre-commit/issues/2451
=> Tests: Adjust traceback regexes to allow Python 3.11+ ^^^^^^^

tests/conftest.py
this wasn't all that useful -- and most of it was for checking python 2 things
=> remove warnings checks

pre_commit/clientlib.py, tests/clientlib_test.py
Resolves #2521 
Apologies for the diff - those two classes were just moved up w/o modification
=> extend warning if globs are used instead of regex to local hooks

CONTRIBUTING.md, azure-pipelines.yml, pre_commit/languages/rust.py, tests/languages/rust_test.py, tests/repository_test.py
This adds support for pinning a specific rust version and bootstrapping rust with rustup/rustup-init.
I tried to follow the desired behavior described here: https://github.com/pre-commit/pre-commit/pull/1863#issuecomment-817185697
=> Rust as 1st class language

pre_commit/languages/r.py
Should solve problems detected in #2459.
=> Enforce binary installs also for dependencies in R

pre_commit/git.py
documented via man gitcredentials,  it is used to provide a script/input for git to fetch creds in a no-tty usecase. used among other things by jenkins to pass credentials down to git for authentication.
https://github.com/jenkinsci/git-plugin/blob/1e3488a730a169778ba0863dd4edbb1dc29154a1/README.adoc#git-bindings https://github.com/jenkinsci/git-plugin/blob/9429e7d05df3dbb4060ac6ab4da6538bb0eb50ba/src/main/java/jenkins/plugins/git/GitUsernamePasswordBinding.java#L130
=> allow GIT_ASKPASS as a pass through env var 

pre_commit/languages/rust.py, setup.cfg, tests/repository_test.py
I forgot I named the branch that... It made more sense at the time!
=> Change Rust to install environment with `cargo add` over `toml`

pre_commit/languages/r.py, tests/languages/r_test.py
Closes #2599 by adding ensuring `.exe` suffix to the `Rscript` executable on Windows. But I don't understand if that change breaks current uses or if some versions of Windows / shells just add `.exe. when it's missing while others don't.
Also, I am not sure if it also closes https://github.com/lorenzwalthert/precommit/issues/441 or if the added `~` in the Rscript path is of any harm or not and `ctypes.windll.kernel32.GetLongPathNameW` from the standard library is needed to use get full path.
=> Adapt extension of R executable depending on os

pre_commit/languages/dotnet.py, testing/resources/dotnet_hooks_csproj_prefix_repo/.gitignore, testing/resources/dotnet_hooks_csproj_prefix_repo/.pre-commit-hooks.yaml, testing/resources/dotnet_hooks_csproj_prefix_repo/Program.cs, testing/resources/dotnet_hooks_csproj_prefix_repo/dotnet_hooks_csproj_prefix_repo.csproj, tests/repository_test.py
(Recreated from #2630)
Fixes #2629
=> fix for dotnet hooks with prefixes

pre_commit/languages/dotnet.py
(Recreated from #2631)
Removes `nuget.org` from the default lookup configuration so package resolution is performed against the local `build_dir` only.
This fixes an issue where dotnet attempts to install unwanted packages or older versions, as `nuget.org` has higher precedence than the specified sources.
=> dotnet: ignore nuget source during tool install

pre_commit/clientlib.py, tests/clientlib_test.py, tests/commands/install_uninstall_test.py
this has been producing a warning since july of 2020:
```console
$ pre-commit run flake8 --all-files
[WARNING] normalizing pre-commit configuration to a top-level map.  support for top level list will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
flake8...................................................................Passed
```
this now produces this error:
```console
$ pre-commit run flake8 --all-files
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
=====> Expected a Config map but got a list
Check the log at /home/asottile/.cache/pre-commit/pre-commit.log
```
this can be fixed automatically by running `pre-commit migrate-config`:
```console
$ pre-commit migrate-config
Configuration has been migrated.
$ …
```
=> remove support for top-level list format

pre_commit/clientlib.py, pre_commit/commands/validate_config.py, pre_commit/commands/validate_manifest.py, setup.cfg, tests/clientlib_test.py, tests/commands/validate_config_test.py, tests/commands/validate_manifest_test.py
this has been warning since april of 2022:
```console
$ pre-commit-validate-manifest .pre-commit-hooks.yaml 
[WARNING] pre-commit-validate-manifest is deprecated -- use `pre-commit validate-manifest` instead.
$ pre-commit-validate-config .pre-commit-config.yaml 
[WARNING] pre-commit-validate-config is deprecated -- use `pre-commit validate-config` instead.
```
this will now be an error:
```console
$ pre-commit-validate-manifest .pre-commit-hooks.yaml 
bash: pre-commit-validate-manifest: command not found
$ pre-commit-validate-config .pre-commit-config.yaml 
bash: pre-commit-validate-config: command not found
```
instead use the `pre-commit` sub-commands:
```console
$ pre-commit validate-manifest .pre-commit-hooks.yaml 
$ pre-commit validate-config .pre-commit-config.yaml 
```
=> remove pre-commit-validate-config and pre-commit-validate-manifest

pre_commit/commands/autoupdate.py, pre_commit/commands/try_repo.py, pre_commit/util.py, tests/util_test.py
see also: https://github.com/python/cpython/commit/e9b51c0ad81da1da11ae65840ac8b50a8521373c
=> special rmtree is not needed for TemporaryDirectory in 3.8+

pre_commit/constants.py, pre_commit/repository.py
the additional bookkeeping has been unnecessary since b827694520be0f39bfc0599f3680b6c08b4516cf
unfortunately this will cause a rebuild of all hooks in order to be forward/backward compatible -- shrugs
=> simplify install state

pre_commit/parse_shebang.py, pre_commit/util.py, tests/commands/install_uninstall_test.py, tests/languages/rust_test.py, tests/parse_shebang_test.py
Custom envs can't be passed to `normalize_cmd` which causes `find_executable` to default to `os.environ` -- works as expected when injecting directly `os.environ`.
=> Fix command normalization when a custom env is passed

pre_commit/store.py
now that it is no longer cloned by `language: golang`
=> the local repo no longer needs to be a git repo

pre_commit/commands/run.py, pre_commit/languages/all.py, pre_commit/languages/docker.py, pre_commit/languages/docker_image.py, pre_commit/languages/fail.py, pre_commit/languages/helpers.py, pre_commit/languages/pygrep.py, pre_commit/languages/r.py, pre_commit/languages/script.py, testing/language_helpers.py, tests/languages/r_test.py, tests/repository_test.py
`language: r` acts more like `language: script` so we have to *not* append
the prefix when run with `repo: local`
=> fix r local hooks

pre_commit/languages/ruby.py, tests/languages/ruby_test.py
=> Revert "also ignore Gemfile in project"

pre_commit/commands/run.py, tests/commands/run_test.py
Fixes #2742.
I fixed the one in `run.py`, fixing the bug. Ithen audited the other `git diff` calls to consider whether text conversion would be suitable there. Those using `--name-only` don't need it, since Git skips text conversion in that case. The diff in `_run_hooks` is for human consumption doesn't need it because it's for the human to read.
=> Add `--no-textconv` to `git diff` calls

pre_commit/staged_files_only.py, tests/staged_files_only_test.py
=> only treat exit code 1 as a successful diff

pre_commit/repository.py, pre_commit/store.py, tests/store_test.py
in other languages this order can matter (such as ruby)
=> remove sorting for repo key for additional_deps

pre_commit/clientlib.py, pre_commit/commands/hook_impl.py, pre_commit/constants.py, pre_commit/main.py, testing/util.py, tests/clientlib_test.py, tests/commands/hook_impl_test.py, tests/commands/run_test.py, tests/main_test.py, tests/repository_test.py
=> make --hook-type and stages match

pre_commit/languages/rust.py
this adds a 270 MB registry cache in the output
=> don't set CARGO_HOME in rust

pre_commit/languages/swift.py
Based on this comment: https://github.com/pre-commit/pre-commit/issues/2835#issuecomment-1494873806
Sorry, I'm not a python dev and I don't see how to run unit tests or anything, or even how to test this locally, but looking at the swift docs it seems like this makes sense:
```
$ swift build -help
OVERVIEW: Build sources into binary products
SEE ALSO: swift run, swift package, swift test
USAGE: swift build <options>
OPTIONS:
--package-path <package-path>
Specify the package path to operate on (default current directory). This changes the working directory before any other operation
...
```
=> Change deprecated `swift build` `-C` command line option to replacement `--package-path`

pre_commit/languages/ruby.py
RubyGems allows OS packagers to specify defaults for `--install-dir` and `--bindir` and these take precedence over `GEM_HOME`. The only way to override the defaults is to explicitly specify the options ourselves when running `gem install`.
Examples of OSes where this is the case are RedHat 9.2 and Gentoo.
Fixes #2799.
=> Force gem installation into envdir

.github/workflows/languages.yaml, pre_commit/all_languages.py, pre_commit/languages/haskell.py, tests/languages/haskell_test.py
I'm attempting to follow the other languages and documentation in CONTRIBUTING (which seems outdated) to add Haskell support to pre-commit so I can add hooks for several useful Haskell tools.
I'm running into issues when trying to run tests of my new language, and I'm trying to figure out where I'm going wrong. Can someone provide guidance?
I'm assuming the system has Haskell installed already, the same as Python and attempting to follow the documented interface in CONTRIBUTING as well as I can without adding too many things for a first pass. I'm hitting strange errors where my mock project can be listed, but it seems to be something other than the CWD for the installation (no project file found to do the install of '.').
Please let me know if there is more up-to-date documentation or …
=> Add haskell language support to pre-commit.

tests/lang_base_test.py, tests/xargs_test.py
The tests for `target_concurrency` have a tight dependency on the internals of `xargs.cpu_count`. Instead, split out the tests across two files.
=> Refactor `target_concurrency` tests

pre_commit/languages/node.py
Fixes #1983
---
This PR is our first contribution. We are very open to suggestions and improvements.
This PR was a group effort by Ordina Pythoneers, they would like to thank Ordina for the time to do this.
@SanderBeekhuis
@RoelAdriaans
@Coen-Smulders
=> Use the --include command, hides warning messages

tests/languages/golang_test.py, tests/languages/node_test.py
On riscv64, nodeenv will pull binary from unofficial-builds [1], and unfortunately 18.13.0 seems to be the only version above 18 that is missing riscv64 builds. Shifting the version slightly to make test work.
Go's binary now ships with linux/riscv64 binary since 1.21.
=> Bump Node.js version to 18.14.0 and Go to 1.21.1

tests/parse_shebang_test.py
the GHA runners now have echo.exe in a path with spaces
=> use sys.executable instead of echo.exe in parse_shebang

pre_commit/commands/run.py, tests/commands/run_test.py, tests/commands/try_repo_test.py
Use `time.monotonic()` to prevent clock slippage error ~, and always output two significant figures to avoid ambiguity~.
=> Improve hook duration timing

.github/workflows/main.yml, pre_commit/util.py
<blockquote>
<p><a href="https://docs.python.org/3.12/library/shutil.html#shutil.rmtree"><code>shutil.rmtree()</code></a> now accepts a new argument <em>onexc</em> which is an
error handler like <em>onerror</em> but which expects an exception instance
rather than a <em>(typ, val, tb)</em> triplet. <em>onerror</em> is deprecated and
will be removed in Python 3.14.
(Contributed by Irit Katriel in <a class="reference external" href="https://github.com/python/cpython/issues/102828">gh-102828</a>.)</p>
</blockquote>
https://docs.python.org/3.12/whatsnew/3.12.html#shutil
=> Address deprecation warning in `shutil.rmtree(onerror=...)`

pre_commit/commands/run.py, tests/commands/run_test.py
=> fix per-hook fail_fast to not fail on previous failures

pre_commit/all_languages.py, pre_commit/languages/julia.py, tests/languages/julia_test.py
This patch adds 2nd class support for hooks using julia as the language. pre-commit will install any dependencies defined in the hooks repo `Project.toml` file, with support for `additional_dependencies` as well. Julia doesn't (yet) have a way to install binaries/scripts so for julia hooks the `entry` value is a (relative) path to a julia script within the hooks repository. When executing a julia hook the (globally installed) julia interpreter is prepended to the entry.
Example `.pre-commit-hooks.yaml`:
```yaml
- id: foo
name: ...
language: julia
entry: bin/foo.jl --arg1
```
Example hooks repo: https://github.com/fredrikekre/runic-pre-commit/tree/fe/julia
Accompanying pre-commit.com PR: https://github.com/pre-commit/pre-commit.com/pull/998
Fixes #2689.
=> Add support for julia hooks

pre_commit/languages/golang.py, tests/languages/golang_test.py
Resolves #3300 
I only disabled the toolchain switching if the version is not `system`. I did this because `system` is the default if go is installed globally and no `language_version` is explicitly specified.  In this case users likely doesn't care which version of go is used as long as their hooks are working, so I think it makes more sense to allow the toolchain switching since it doesn't break user expectations and other than a small performance hit on hook installation doesn't have negative impact.
If we were to disable toolchain switching regardless of the version, many hooks would break since many environments lag with their go version. For example, in GitHub-hosted runners for GitHub Actions the pre-installed go version is `1.21` which is two versions behind the current version, …
=> disable automatic toolchain switching for golang hooks

tests/languages/dotnet_test.py
.net 6 and 7 were removed from github actions runners
=> update .net tests to use .net 8

pre_commit/languages/r.py, tests/languages/r_test.py
Closes #3385. The bug is that in `install_environment()`, the env patch was not applied in the following snippet:
```python
with _r_code_in_tempfile(r_code_inst_environment) as f:
cmd_output_b(_rscript_exec(), '--vanilla', f, cwd=env_dir)
```
The existing `_execute_vanilla_r_code_as_script()` abstracting away 
1) the application of env patch and
1) the writing inline code to file and executing there (since [inline execution lead to parser failures](https://github.com/pre-commit/pre-commit/issues/2870)) 
was only suitable to execute R code *after* the environment has been installed and was for that reason not used when the renv environment was set up initially. 
Hence, the approach I took was to factor out `_execute_r()` that does 1. and 2. and can be parametrised as far as CLI options …
=> Fix language:r hook installation when initiated in RStudio

pre_commit/git.py, tests/git_test.py
I lost the log when I faced this crash, but it was of the form:
```
CalledProcessError: ('git', 'diff', '--name-only', '--no-ext-diff', '-z', '-m', '1234abc', 'HEAD', 'MERGE_HEAD'): Ambiguous reference 'HEAD'
... something about prepending '--', like
git diff ref [ref2] -- [files]
```
Likely happened because there is a folder named `head` in the base commit SHA.
And this fixes the issue. If you have more information on how I can create a minimal reproduction of the bug and add it as a test, I'd be happy to.
=> fix: crash on ambiguous ref 'HEAD'
