pre-commit/pre-commit

appveyor.yml
pre_commit/commands/clean.py
pre_commit/five.py
pre_commit/git.py
pre_commit/languages/node.py
pre_commit/languages/python.py
pre_commit/logging_handler.py
pre_commit/make_archives.py
pre_commit/output.py
pre_commit/store.py
pre_commit/util.py
testing/resources/system_hook_with_spaces_repo/hooks.yaml
testing/util.py
tests/commands/clean_test.py
tests/commands/install_uninstall_test.py
tests/commands/run_test.py
tests/error_handler_test.py
tests/languages/ruby_test.py
tests/prefixed_command_runner_test.py
tests/repository_test.py
tests/runner_test.py
tests/store_test.py

This gets a minimally viable product working under windows.
There are some things I've decided to punt on and fix in a v2, notably:
- coloring
- matching terminal width
- node support
- ruby support
- pcre support
I'll ticket these separately if this is good enough to ship :)

Windows MVP

---

pre_commit/store.py

Use reset instead of checkout when checking out hook repo

---

pre_commit/clientlib/validate_config.py
pre_commit/commands/run.py
pre_commit/repository.py
testing/fixtures.py
tests/clientlib/validate_config_test.py
tests/commands/run_test.py
tests/repository_test.py
tests/runner_test.py

Closes #219
All tests pass and coverage for new file `pre_commit/hook_executor.py` is 100%

Adding support for locally-defined hooks

---

.pre-commit-config.yaml
pre_commit/clientlib/validate_base.py
tox.ini

seems like a good idea. not sure if there's some edge case where this doesn't make sense (or where it needs to be a separate target)?

Run this repo's pre-commit hooks in tox (and thus travis)

---

pre_commit/languages/pcre.py

This fixes issue https://github.com/pre-commit/pre-commit/issues/133

Use ggrep instead of grep for pcre on mac os

---

requirements-dev.txt
testing/fixtures.py
tests/commands/autoupdate_test.py
tests/commands/install_uninstall_test.py
tests/commands/run_test.py
tests/conftest.py
tests/git_test.py
tests/main_test.py
tests/make_archives_test.py
tests/manifest_test.py
tests/repository_test.py
tests/runner_test.py
tests/staged_files_only_test.py
tests/store_test.py

git grep -l tmpdir_factory | xargs sed -i 's/tmpdir_factory/tempdir_factory/g'

---

.gitignore

pytest 2.8 introduces this directory

gitignore: add .cache

---

.travis.yml
testing/resources/ruby_1_9_3_hooks_repo/hooks.yaml
tests/repository_test.py
tox.ini

- Improve ruby version test on 14.04 by picking a binary that exists (it also exists on 12.04 (travis-ci))
- Utilize travis-ci caches

Some speedups for tests

---

tests/commands/run_test.py

Sorry, a VERY slight correction to the test I made.

Corrected stages integration test

---

tox.ini

Looks like this started running twice since @chriskuehl added pre-commit running pre-commit in #252
fixd!

Don't run flake8 twice

---

CHANGELOG.md
pre_commit/clientlib/validate_config.py
pre_commit/languages/node.py
pre_commit/languages/pcre.py
pre_commit/languages/python.py
pre_commit/languages/ruby.py
pre_commit/languages/script.py
pre_commit/languages/system.py
pre_commit/repository.py
setup.py
tests/languages/all_test.py
tests/repository_test.py

Added the ability to specify additional dependencies to be installed in
the pre-commit environment.

Added the additional_dependencies config parameter

---

pre_commit/error_handler.py
tests/error_handler_test.py

Fix printing of non-ascii in error handler

---

pre_commit/clientlib/validate_manifest.py
pre_commit/repository.py
testing/fixtures.py
tests/manifest_test.py
tests/repository_test.py

Add an option to require a specific pre-commit version

---

tests/conftest.py

Can't remember why I added this, tests pass without it :S

Remove adding config file in one place

---

pre_commit/repository.py
setup.py
tests/repository_test.py

Make additional_dependencies rollforward safe

---

pre_commit/git.py
tests/git_test.py
tests/runner_test.py

Use rev-parse --show-toplevel

---

pre_commit/git.py
pre_commit/main.py
pre_commit/runner.py
tests/commands/install_uninstall_test.py
tests/conftest.py
tests/git_test.py
tests/runner_test.py

Support pre-commit from inside submodules

---

pre_commit/error_handler.py
pre_commit/languages/node.py
pre_commit/languages/python.py
pre_commit/languages/ruby.py
pre_commit/util.py
testing/resources/not_installable_repo/hooks.yaml
testing/resources/not_installable_repo/setup.py
tests/commands/run_test.py
tests/error_handler_test.py

Fail gracefully on undecodable install output.

---

pre_commit/git.py
testing/test_symlink
tests/git_test.py

os.path.exists -> os.path.lexists so that we also check symlink files

include checking symlinks

---

pre_commit/main.py

Add choices to --color help text.
Fix typo in --allow-unstaged-config.

Improve help text

---

pre_commit/parse_shebang.py
pre_commit/util.py
testing/resources/not_found_exe/hooks.yaml
tests/parse_shebang_test.py
tests/repository_test.py

Don't crash when an executable is not found

---

.travis.yml
setup.py
tox.ini

There's a lot of cleanup to do after this, but for now let's stop testing to unblock other PRs

Stop supporting python2.6  Resolves #263

---

pre_commit/languages/ruby.py
pre_commit/make_archives.py
pre_commit/util.py
tests/make_archives_test.py

Remove tarfile_open (tarfile open in 2.7+)

---

tests/staged_files_only_test.py

See #409
Resolves #410 
CC @samsaggace

Add regression test for external diff tools

---

pre_commit/clientlib/validate_base.py
pre_commit/clientlib/validate_config.py
pre_commit/clientlib/validate_manifest.py
pre_commit/color.py
pre_commit/commands/autoupdate.py
pre_commit/commands/clean.py
pre_commit/commands/install_uninstall.py
pre_commit/commands/run.py
pre_commit/languages/helpers.py
pre_commit/languages/node.py
pre_commit/languages/python.py
pre_commit/languages/ruby.py
pre_commit/logging_handler.py
pre_commit/main.py
pre_commit/make_archives.py
pre_commit/output.py
pre_commit/parse_shebang.py
pre_commit/repository.py
pre_commit/staged_files_only.py
pre_commit/store.py
pre_commit/util.py
testing/resources/python3_hooks_repo/python3_hook/main.py
tests/clientlib/validate_config_test.py
tests/color_test.py
tests/commands/run_test.py
tests/languages/python_test.py
tests/parse_shebang_test.py
tests/repository_test.py

Remove py26 format literals

---

pre_commit/languages/pcre.py
pre_commit/parse_shebang.py
pre_commit/util.py
pre_commit/xargs.py
tests/repository_test.py
tests/util_test.py
tests/xargs_test.py

xargs returns nonzero for negate + not found exe (fixes pcre + not found #447)

---

pre_commit/languages/docker.py

@bpicolo 
I did a tiny bit of profiling and I think this goes better with the design of pre-commit.  It's a pretty minor change but makes a big difference :D
```
$ time pre-commit run --all-files -v
[flake8] Flake8..............................................................Failed
hookid: flake8
test.py:1:5: F821 undefined name 'y'
[flake8-docker-not-for-production] flake8 (via docker).......................Failed
hookid: flake8-docker-not-for-production
test.py:1:5: F821 undefined name 'y'
real	0m1.908s
user	0m0.472s
sys	0m0.072s
```
```
$ time pre-commit run --all-files -v
[flake8] Flake8..............................................................Failed
hookid: flake8
test.py:1:5: F821 undefined name 'y'
[flake8-docker-not-for-production] flake8 (via …
```

Only --pull on initial docker build

---

pre_commit/languages/docker.py
pre_commit/languages/helpers.py
pre_commit/languages/node.py
pre_commit/languages/python.py
pre_commit/languages/ruby.py
pre_commit/languages/script.py
pre_commit/languages/system.py

Make shlex behaviour of entry more consistent

---

pre_commit/languages/ruby.py
tests/repository_test.py

Fix ruby hooks in projects with weird options in.bundle/config

---

pre_commit/languages/golang.py

Forgot to remove these before merging :)

The golang tests pass on windows

---

pre_commit/languages/golang.py
tests/repository_test.py

additional_dependencies support for golang hooks

---

pre_commit/languages/docker.py

Put the `.` in docker build at the end.

---

testing/util.py

@tdeo I cherry picked this out of your PR

PCRE tests work on osx

---

pre_commit/constants.py
pre_commit/store.py

Encode the 'local hooks repo' version into the store

---

pre_commit/commands/run.py
pre_commit/main.py
tests/commands/run_test.py

Add a --show-diff-on-failure option

---

pre_commit/commands/sample_config.py
pre_commit/main.py
tests/commands/sample_config_test.py
tests/main_test.py

Add a `pre-commit sample-config` command

---

pre_commit/main.py
tests/conftest.py
tests/main_test.py
tests/repository_test.py

Make autoupdate --tags-only the default, add --bleeding-edge

---

pre_commit/git.py
tests/commands/install_uninstall_test.py
tests/git_test.py

Fix non-ascii merge commit messages in python2

---

pre_commit/commands/run.py

Hi this is a tiny change to fix #533
Cheers

Fix for #533

---

pre_commit/commands/run.py
pre_commit/git.py
pre_commit/staged_files_only.py

Run git diff with --no-ext-diff

---

pre_commit/commands/run.py

Expose --source and --origin as environment variables

---

.pre-commit-config.yaml
CONTRIBUTING.md
pre_commit/languages/ruby.py
testing/fixtures.py
tests/clientlib_test.py
tests/color_test.py
tests/commands/run_test.py
tests/prefixed_command_runner_test.py
tests/runner_test.py

I also removed the blurb from CONTRIBUTING.md since it is automatically enforced now.

Upgrade add-trailing-comma to 0.4.0

---

pre_commit/commands/install_uninstall.py
pre_commit/commands/run.py
pre_commit/main.py
pre_commit/resources/commit-msg-tmpl
pre_commit/resources/hook-tmpl
testing/fixtures.py
tests/commands/install_uninstall_test.py
tests/commands/run_test.py
tests/conftest.py

Add support for commit-msg git hook

---

pre_commit/main.py

Allow commit-msg hooks to be uninstalled

---

pre_commit/commands/run.py
pre_commit/main.py
tests/commands/run_test.py
tests/git_test.py

Remove --no-stash and --allow-unstaged-config

---

pre_commit/file_lock.py
pre_commit/store.py
tests/commands/install_uninstall_test.py
tests/repository_test.py
tests/store_test.py

Only print that the lock is being acquired when waiting

---

pre_commit/commands/run.py
pre_commit/git.py
tests/commands/run_test.py
tests/git_test.py

Handle non-ascii filenames from git

---

pre_commit/commands/install_uninstall.py
pre_commit/resources/commit-msg-tmpl
pre_commit/resources/hook-tmpl
pre_commit/resources/pre-push-tmpl
tests/commands/install_uninstall_test.py

Via `pre-commit install -c .other-config.yaml`

Fix specify config file not work while installing

---

.travis.yml
appveyor.yml
pre_commit/commands/clean.py
pre_commit/error_handler.py
pre_commit/store.py
tests/commands/clean_test.py
tests/error_handler_test.py
tests/main_test.py
tests/store_test.py

Adhere to XDG specification for cache dir.

---

pre_commit/clientlib.py
pre_commit/commands/autoupdate.py
pre_commit/commands/run.py
pre_commit/runner.py
pre_commit/schema.py
tests/commands/autoupdate_test.py
tests/commands/run_test.py
tests/schema_test.py

Implement `fail_fast`.

---

pre_commit/clientlib.py
pre_commit/commands/run.py
pre_commit/git.py
tests/commands/run_test.py
tests/git_test.py

Implement global exclude

---

pre_commit/languages/python.py

suggested here: https://github.com/tox-dev/tox/issues/501#issuecomment-329545531

Also check the ssl module for virtualenv health.

---

pre_commit/staged_files_only.py
tests/staged_files_only_test.py

Do not crash in staged_files_only if patch_dir does not exist

---

setup.py

Include all resources

---

pre_commit/commands/run.py
pre_commit/runner.py

Lazily install repositories

---

CONTRIBUTING.md
testing/util.py
tests/make_archives_test.py
tests/repository_test.py

It wasn't actually working because of tox, I also don't use this.

Remove slowtests=false setting

---

pre_commit/meta_hooks/check_hooks_apply.py
tests/meta_hooks/check_hooks_apply_test.py

CC @hackedd, just a tiny edge case I thought of while writing up the changelog

always_run hooks always apply to the repository

---

pre_commit/commands/autoupdate.py
pre_commit/main.py
tests/commands/autoupdate_test.py

Aims to add the feature brought up in https://github.com/pre-commit/pre-commit/issues/656

Add repo option to autoupdate

---

pre_commit/store.py
tests/repository_test.py

Fix broken local golang repos

---

pre_commit/commands/run.py
tests/commands/run_test.py

Deprecate the pcre language

---

CHANGELOG.md
CONTRIBUTING.md
README.md
pre_commit/commands/sample_config.py
pre_commit/main.py
pre_commit/parse_shebang.py
pre_commit/store.py
tests/commands/sample_config_test.py

- A lot of http links loaded fine on https
- pre-commit.com is now loadable on https via cloudflare

https-ify links

---

tests/commands/autoupdate_test.py
tests/commands/run_test.py
tests/conftest.py
tests/error_handler_test.py
tests/main_test.py
tests/staged_files_only_test.py

Replace deprecated yield_fixture with fixture

---

pre_commit/resources/pre-push-tmpl
tests/commands/install_uninstall_test.py

Fix bad check for ancestor root commits.

Properly detect if commit is a root commit

---

pre_commit/commands/install_uninstall.py
tests/commands/install_uninstall_test.py

Refuse to install with core.hooksPath set

---

pre_commit/clientlib.py
pre_commit/constants.py
pre_commit/main.py
tests/commands/run_test.py
tests/conftest.py

Add a manual stage for cli-only interaction

---

MANIFEST.in

Add MANIFEST file to include license in sdist

---

CONTRIBUTING.md

pytest: drop the dot!

---

pre_commit/languages/python_venv.py

Invoke -mvenv with the original python if in a -mvirtualenv venv

---

.travis.yml
setup.py

tried this [here](https://test.pypi.org/project/pre_commit/1.10.1.post2/) seems to work.

Include README as long_description

---

pre_commit/resources/hook-tmpl
tests/commands/install_uninstall_test.py

Fix force-push without fetch

---

pre_commit/parse_shebang.py
tests/parse_shebang_test.py

Improve not found error with script paths (`./exe`)

---

pre_commit/languages/python_venv.py

Default to python3 when using python_venv under python 2

---

testing/util.py

This reverts commit 063014ffd833ea8ac6a8fa47e6c95582d6ff2247, reversing
changes made to 259ef9e53041b43e746da5b2b1fe5ca9020d70fe.
Resolves #798

Revert "Merge pull request #799 from pre-commit/temporarily_skip_npm_windows"

---

pre_commit/languages/all.py
pre_commit/languages/fail.py
tests/repository_test.py

Add language: fail

---

pre_commit/git.py

Fix rev-parse for older git versions

---

pre_commit/resources/hook-tmpl
tests/commands/install_uninstall_test.py

fix pushing to new branch not identifying all commits

---

tests/meta_hooks/check_hooks_apply_test.py

I noticed there was some missing test coverage.  This fixes it

Improve coverage of check_hooks_apply

---

pre_commit/commands/autoupdate.py
tests/commands/autoupdate_test.py

Reraises InvalidManifestError as RepositoryCannotBeUpdatedError

---

pre_commit/languages/helpers.py
tests/languages/helpers_test.py

Shuffle arguments before running hooks

---

pre_commit/commands/install_uninstall.py
tests/commands/install_uninstall_test.py

Pick a better python shebang for hook executable

---

pre_commit/meta_hooks/identity.py
pre_commit/repository.py
tests/meta_hooks/identity_test.py

Add identity meta hook

---

.pre-commit-config.yaml
.travis.yml
pre_commit/commands/autoupdate.py
pre_commit/commands/install_uninstall.py
pre_commit/commands/run.py
pre_commit/meta_hooks/check_hooks_apply.py
pre_commit/meta_hooks/check_useless_excludes.py
pre_commit/meta_hooks/helpers.py
pre_commit/meta_hooks/identity.py
pre_commit/repository.py
setup.py
testing/resources/ruby_versioned_hooks_repo/.pre-commit-hooks.yaml
tests/commands/run_test.py
tests/repository_test.py

this cuts off ~10% of startup time (cached_property imports asyncio! what!)
this also will enable threading through top level configuration to influence the hook setup so I can implement a few features I've been meaning to do

Refactor pre_commit.repository and factor out cached-property

---

pre_commit/commands/run.py
pre_commit/commands/try_repo.py
pre_commit/git.py
pre_commit/logging_handler.py
pre_commit/main.py
pre_commit/store.py
pre_commit/util.py
testing/fixtures.py
tests/commands/try_repo_test.py
tests/conftest.py
tests/git_test.py
tests/main_test.py

Teach pre-commit try-repo to clone uncommitted changes

---

pre_commit/commands/gc.py
pre_commit/error_handler.py
pre_commit/main.py
pre_commit/store.py
testing/fixtures.py
tests/clientlib_test.py
tests/commands/autoupdate_test.py
tests/commands/clean_test.py
tests/commands/gc_test.py
tests/commands/run_test.py
tests/main_test.py
tests/store_test.py

pre-commit gc

---

.pre-commit-config.yaml
pre_commit/clientlib.py
pre_commit/commands/autoupdate.py
pre_commit/commands/gc.py
pre_commit/commands/install_uninstall.py
pre_commit/constants.py
pre_commit/languages/all.py
pre_commit/languages/docker.py
pre_commit/languages/golang.py
pre_commit/languages/helpers.py
pre_commit/languages/node.py
pre_commit/languages/python.py
pre_commit/languages/ruby.py
pre_commit/languages/rust.py
pre_commit/languages/swift.py
pre_commit/repository.py
pre_commit/xargs.py
tests/clientlib_test.py
tests/commands/gc_test.py
tests/commands/install_uninstall_test.py
tests/languages/helpers_test.py
tests/repository_test.py
tests/xargs_test.py

Implement default_language_version

---

setup.py

should have done this in #908 but I forgot

bump cfgv, forgot in last PR

---

pre_commit/git.py
pre_commit/staged_files_only.py
tests/git_test.py
tests/staged_files_only_test.py

Fix staged-files-only for `git add --intent-to-add` files

---

pre_commit/languages/python.py
tests/languages/python_test.py

Use sys.executable if it matches the requested version

---

pre_commit/commands/install_uninstall.py
tests/commands/install_uninstall_test.py

see Homebrew/homebrew-core#35825

Be more timid about choosing a shebang

---

testing/util.py

This reverts commit 45a34d6b7543563c3cda847428aebefde269310d, reversing
changes made to d0c62aae7a93e3bd14eba7d131c15b4211201ef3.
Resolves #887

Revert "Merge pull request #888 from pre-commit/887_xfail_windows_node_again"

---

.pre-commit-config.yaml
pre_commit/xargs.py
tests/conftest.py

Migrate to official pycqa/flake8 hooks repo

---

pre_commit/git.py

pass GIT_SSH_COMMAND to git commands

---

pre_commit/languages/node.py

Use npm install git+file:// instead of npm install .

---

pre_commit/xargs.py
tests/xargs_test.py

Compute the maximum command length more accurately

---

pre_commit/languages/node.py
pre_commit/store.py
testing/util.py
tests/store_test.py

Closes #918 
Needs some cleaning up, especially the name "_perform_safe_clone" doesn't really represent the function's purpose. I'm open for suggestions.

Allow shallow cloning

---

pre_commit/clientlib.py
tests/clientlib_test.py

Add top level minimum_pre_commit_version

---

.pre-commit-config.yaml
pre_commit/commands/autoupdate.py
pre_commit/commands/install_uninstall.py
pre_commit/commands/run.py
pre_commit/git.py
pre_commit/make_archives.py
tests/clientlib_test.py
tests/conftest.py
tests/languages/ruby_test.py
tests/parse_shebang_test.py
tests/repository_test.py

Run pre-commit autoupdate

---

pre_commit/commands/run.py
tests/commands/run_test.py

change for issue: https://github.com/pre-commit/pre-commit/issues/968
also add Pipfile to .gitignore for pipenv users

add helpful CI message

---

pre_commit/xargs.py

See https://github.com/pre-commit/pre-commit/issues/691#issuecomment-478454161

Bound maxsize by 4096 when SC_ARG_MAX is not present

---

pre_commit/store.py
tests/store_test.py

Fix full clone + non-mainline tag

---

pre_commit/commands/install_uninstall.py
tests/commands/install_uninstall_test.py

Fix double legacy install on windows

---

testing/util.py

I'm still a beginner, but a single single quote looked a bit off to me.
Could adding another single quote after pre fix this issue?

Could this fix #1013?

---

pre_commit/languages/python.py

Don't attempt to decode the healthy response

---

pre_commit/error_handler.py
tests/error_handler_test.py

Extracted the parts I'm more sure about from #1027

Improve output when interrupted (^C)

---

pre_commit/util.py
tests/util_test.py

Fix rmtree for readonly directories

---

azure-pipelines.yml
tests/commands/install_uninstall_test.py

Fix test_environment_not_sourced when pre-commit is installed globally

---

pre_commit/clientlib.py
pre_commit/repository.py
setup.cfg
tests/clientlib_test.py
tests/repository_test.py

See https://github.com/asottile/cfgv/pull/18 for context
I wanted to improve the warning messages here to include some context

fixes for cfgv>=2

---

pre_commit/commands/run.py
tests/commands/run_test.py

Pass color option to git diff (on failure)

---

pre_commit/commands/autoupdate.py
pre_commit/git.py
pre_commit/store.py
tests/commands/gc_test.py

Fix autoupdate to always use non-shallow clone

---

pre_commit/commands/init_templatedir.py
pre_commit/commands/install_uninstall.py
pre_commit/main.py
tests/commands/init_templatedir_test.py
tests/commands/install_uninstall_test.py
tests/conftest.py
tests/main_test.py

Implement `pre-commit init-templatedir`

---

pre_commit/color.py
tests/color_test.py

Don't use color if NO_COLOR environment variable is set

---

pre_commit/color.py
tests/color_test.py

Disable color if TERM=dumb is detected

---

pre_commit/main.py
tests/main_test.py

accidentally regressed in #1145

Fix hook_types when calling init-templatedir

---

pre_commit/languages/fail.py
tests/repository_test.py

accidentally regressed in #1168

Fix fail type signature

---

pre_commit/commands/run.py
tests/commands/run_test.py

Normalize paths on windows to forward slashes

---

pre_commit/store.py

Fix rare first-run race with creation of pre-commit directory

---

azure-pipelines.yml
pre_commit/main.py

See https://github.com/microsoft/azure-pipelines-yaml/issues/409

Fix step template breakage

---

pre_commit/clientlib.py
pre_commit/commands/run.py
tests/commands/run_test.py

Add top-level `files` key for inclusion

---

pre_commit/util.py
tests/languages/docker_test.py
tests/store_test.py
tests/util_test.py

A few cleanups for CalledProcessError to hopefully make it more readable

---

testing/util.py
tests/commands/init_templatedir_test.py
tests/commands/install_uninstall_test.py
tests/commands/run_test.py
tests/commands/try_repo_test.py
tests/conftest.py
tests/error_handler_test.py

hopefully fewer places that I keep making this mistake 🙃

Normalize crlf in tests

---

pre_commit/constants.py
pre_commit/main.py
pre_commit/resources/hook-tmpl
testing/util.py
tests/commands/install_uninstall_test.py
tests/repository_test.py

new in git 2.24 -- need to figure out the right way to gate this though

support pre-merge-commit

---

pre_commit/clientlib.py
pre_commit/commands/autoupdate.py
pre_commit/main.py
tests/commands/autoupdate_test.py
tests/commands/gc_test.py

Implement `pre-commit autoupdate --freeze`

---

pre_commit/commands/autoupdate.py

Fixes #1261. 
I added a space after as well in order to make it look more balanced.

Make URL clickable

---

pre_commit/main.py
tests/main_test.py

Remove autoupdate --tags-only option

---

pre_commit/commands/install_uninstall.py
tests/commands/init_templatedir_test.py

allow init-templatedir to succeed when core.hooksPath is set

---

pre_commit/commands/install_uninstall.py
tests/commands/install_uninstall_test.py

Improve git hook shebang creation

---

tests/commands/run_test.py

I swear it was green when I merged #1344 🤔

Fix test coverage

---

pre_commit/color.py
tests/color_test.py

support colors on windows during git better

---

pre_commit/commands/hook_impl.py
tests/commands/hook_impl_test.py

validate argument length as part of hook-impl

---

pre_commit/languages/python.py

Allow pip to be upgradable on windows

---

pre_commit/commands/hook_impl.py
pre_commit/commands/run.py
pre_commit/constants.py
pre_commit/main.py
tests/commands/hook_impl_test.py
tests/commands/install_uninstall_test.py
tests/repository_test.py

Implement post-commit as an additional git hook. 
This will close #1411.

Implement post-commit

---

pre_commit/commands/run.py
pre_commit/staged_files_only.py
testing/util.py
tests/commands/install_uninstall_test.py
tests/commands/run_test.py

pass through an environment variable to prevent hooks running
Fixes #1418.

fix hooks firing during staged_files_only

---

pre_commit/store.py
tests/store_test.py

Use the real path of the cache root

---

pre_commit/commands/migrate_config.py
tests/commands/migrate_config_test.py

refuse to migrate an invalid configuration

---

pre_commit/commands/run.py
tests/commands/run_test.py

Expose an env variable that indicates if pre-commit is running

---

pre_commit/languages/python.py

avoid a UnicodeError on windows with non-charmap characters

---

azure-pipelines.yml
pre_commit/languages/helpers.py
tests/languages/helpers_test.py

use the shuffle method of Random instead

---

azure-pipelines.yml
pre_commit/languages/ruby.py
testing/util.py
tests/languages/ruby_test.py
tests/repository_test.py

skip rbenv if ruby and gem are installed with default language_version

---

pre_commit/languages/node.py
tests/repository_test.py

fix node hooks when NPM_CONFIG_USERCONFIG is set

---

pre_commit/error_handler.py
tests/error_handler_test.py

better error handling when Store is readonly

---

pre_commit/languages/python.py
tests/languages/python_test.py

fix cache of invalidated unhealthy environment version info

---

pre_commit/languages/node.py
tests/languages/node_test.py

fix for node healthy() when system executable moves

---

pre_commit/commands/install_uninstall.py
tests/commands/install_uninstall_test.py

See issue #1583 for discussion. This PR right now is just to trigger automatic testing on the pipeline and check results.

Drop python.exe extension on windows in shebang line to fix pyenv-win setup

---

pre_commit/clientlib.py
pre_commit/error_handler.py
pre_commit/errors.py
pre_commit/git.py
pre_commit/main.py
tests/error_handler_test.py
tests/main_test.py

check cygwin mismatch earlier

---

CHANGELOG.md
pre_commit/languages/conda.py
tests/xargs_test.py

found via `pre-commit  try-repo https://github.com/codespell-project/codespell --all-files`

fix a few spelling errors

---

requirements-dev.txt
testing/zipapp/Dockerfile
testing/zipapp/entry
testing/zipapp/fakepython
testing/zipapp/make
testing/zipapp/python

seems to work!
```console
$ ./pre-commit-2.7.1.pyz run flake8 --all-files
flake8...................................................................Passed
```

add zipapp support

---

pre_commit/languages/node.py
tests/languages/node_test.py

this is for fixing pre-commit-ci/issues#2

improve node install by using npm pack

---

pre_commit/languages/helpers.py
pre_commit/languages/node.py
pre_commit/languages/ruby.py
tests/languages/helpers_test.py

don't use system for ruby/node if it is a shim exe

---

pre_commit/languages/ruby.py
tests/languages/ruby_test.py

don't call rbenv install for language_version = default

---

pre_commit/xargs.py
tests/xargs_test.py

see https://github.com/pre-commit/pre-commit/issues/1604#issuecomment-723197003

improve xargs when running windows batch files

---

pre_commit/languages/ruby.py

fix for rbenv used outside of pre-commit and language_version: default

---

pre_commit/commands/autoupdate.py

fixed message if repo couldn't be updated due to missing hook(s)

---

pre_commit/git.py

Resolves #1610
Git 2.25 introduced a change to "rev-parse --show-toplevel" that exposed underlying volumes for Windows drives mapped with SUBST.  We use "rev-parse --show-cdup" to get the appropriate path, but must perform an extra check to see if we are in the .git directory.

git: changed rev-parse option for Git 2.25 changes to --show-toplevel

---

pre_commit/git.py
tests/git_test.py
tests/main_test.py

fix execution in worktrees in subdirectories of bare repositories

---

tests/git_test.py

add test for worktree inside of .git dir

---

pre_commit/languages/r.py

In #1799, we assume `env_dir` instead of `prefix_dir` as the package source and install it, which creates a package with the right name (because of `DESCRIPTION`), but obviously does not expose any API and is hence useless. Hooks that rely on the installed package hence fail. ~Also removing an [(apparently) randomly introduced `\`](https://github.com/pre-commit/pre-commit/compare/master...lorenzwalthert:renv-fix#diff-813c025754186e7d7af82275ff89a79dd4bce3f2e037190c30c2f5a1aa1c8a9dL97) that does not cause any harm.~

Fix r hooks when hook repo is a package 

---

pre_commit/staged_files_only.py

Include PID in patch filename

---

CHANGELOG.md
pre_commit/resources/empty_template_Makefile.PL
pre_commit/resources/empty_template_go.mod
pre_commit/resources/empty_template_package.json
pre_commit/resources/empty_template_pre_commit_dummy_package.gemspec
pre_commit/resources/empty_template_pre_commit_placeholder_package.gemspec
pre_commit/resources/empty_template_setup.py
pre_commit/store.py
tests/commands/run_test.py
tests/conftest.py
tests/languages/ruby_test.py

Use more inclusive language

---

pre_commit/languages/docker.py
tests/languages/docker_test.py

ignore self-container when in docker-in-docker

---

.github/ISSUE_TEMPLATE/bug.yaml

I'm going to try this out and see if it improves issue quality, if not I can always back it out or improve it 🤷

add a bug report issue form

---

pre_commit/commands/autoupdate.py
pre_commit/git.py
tests/commands/autoupdate_test.py

fix pre-commit autoupdate for core.useBuiltinFSMonitor=true on windows

---

tests/repository_test.py

these have been reasonably stable for a while

un-xfail node on windows

---

pre_commit/commands/install_uninstall.py
pre_commit/commands/run.py
tests/commands/install_uninstall_test.py

via https://github.com/asottile/dead

run dead, remove dead code

---

pre_commit/git.py

GIT_HTTP_PROXY_AUTHMETHOD kept in env variables

---

pre_commit/languages/coursier.py

On some systems, the executable might be named `coursier` instead of
`cs`. For example, this is the case on Arch Linux when using the AUR
package, or when following the official instructions when installing the
JAR-based launcher:
https://get-coursier.io/docs/cli-installation#jar-based-launcher

coursier: Add support for both `cs` and `coursier` executable names

---

pre_commit/staged_files_only.py

there's a rare race outlined in #2287
resolves #2287

move patch discarding inside `try` for staged_files_only

---

pre_commit/commands/run.py
tests/commands/run_test.py

respect aliases in SKIP when installing environments

---

tests/clientlib_test.py

Cleanup from #2524 - not sure why this made it in here

remove extraneous raw string literal in test

---

pre_commit/git.py

Change `intent_to_add_files` from using `git status` to `git diff`

---

pre_commit/languages/r.py
tests/languages/r_test.py

this wasn't meant to be read -- hook.prefix works fine for local too

avoid using hook.src in R language

---

pre_commit/languages/conda.py
pre_commit/languages/coursier.py
pre_commit/languages/dart.py
pre_commit/languages/docker.py
pre_commit/languages/dotnet.py
pre_commit/languages/golang.py
pre_commit/languages/lua.py
pre_commit/languages/node.py
pre_commit/languages/perl.py
pre_commit/languages/python.py
pre_commit/languages/r.py
pre_commit/languages/ruby.py
pre_commit/languages/rust.py
pre_commit/languages/swift.py
pre_commit/repository.py

diff is best viewed with [?w=1](https://github.com/pre-commit/pre-commit/pull/2668/files?w=1)

move clean_path_on_failure out of each hook install

---

pre_commit/constants.py
pre_commit/repository.py

Reverts pre-commit/pre-commit#2671

Revert "simplify install state"

---

pre_commit/commands/migrate_config.py
tests/commands/migrate_config_test.py

eagerly catch invalid yaml in migrate-config

---

pre_commit/languages/golang.py
testing/resources/golang_hooks_repo/golang-hello-world/main.go
tests/languages/golang_test.py
tests/repository_test.py

Following #2672  
Closes #2649

Make Golang a first class language

---

pre_commit/constants.py
pre_commit/repository.py
tests/repository_test.py

the v1 state is unnecessary since new repos are created for new additional_dependencies

introduce install state v2 to replace v1

---

pre_commit/languages/ruby.py

this starts failing with ruby 3.2.0

also ignore Gemfile in project

---

pre_commit/languages/dotnet.py

see https://github.com/dotnet/sdk/issues/30624#issuecomment-1435457318

future-proof dotnet build command

---

tests/languages/pygrep_test.py
tests/repository_test.py

I feel like I mess up the case-insensitive test, but I'm not sure!

test pygrep inline

---

pre_commit/languages/rust.py

see also https://github.com/pre-commit-ci/issues/issues/173

set RUSTUP_HOME when using a non-system rust

---

pre_commit/languages/rust.py

set CARGO_HOME while executing rustup

---

pre_commit/commands/autoupdate.py
pre_commit/lang_base.py
pre_commit/main.py
pre_commit/xargs.py

add --jobs option to autoupdate

---

pre_commit/commands/autoupdate.py

add partial clone hack to fix autoupdate for windows

---

pre_commit/languages/r.py

Closes #2870. I also fixed a dedention issue in `_inline_r_setup` because if `code` has a different indention than the string we define there. R is indention insensitive but still good to have correct indention.

More robust R hooks for Windows

---

.github/workflows/languages.yaml
.github/workflows/main.yml

the old syntax worked for azure pipelines but not GHA

fix tags trigger for github actions

---

tests/languages/golang_test.py

upstream changed the output here

update hello world go test

---

pre_commit/commands/run.py
pre_commit/meta_hooks/check_hooks_apply.py
pre_commit/meta_hooks/check_useless_excludes.py
tests/commands/run_test.py

Resolves #2935. Renamed some variables to make mypy happier / improve readability

Short-circuit `check-hooks-apply` and `check-useless-excludes` hooks

---

pre_commit/staged_files_only.py
tests/staged_files_only_test.py

reported in https://github.com/pre-commit/pre-commit/issues/2839#issuecomment-1910833889

staged_files_only can handle a crlf-only diff

---

pre_commit/languages/golang.py
tests/languages/golang_test.py

fix building golang hooks during `commit --all`

---

pre_commit/languages/r.py
tests/languages/r_test.py

Support health check for `language: r`

---

pre_commit/commands/migrate_config.py
tests/commands/migrate_config_test.py

migrate-config rewrites deprecated stages

---

pre_commit/clientlib.py
tests/clientlib_test.py

add warning for deprecated stages names

---

.github/workflows/languages.yaml

this was removed in ubuntu-24.04 github actions runner

install r on ubuntu runners

---

.github/workflows/languages.yaml
.github/workflows/main.yml

upgrade asottile/workflows

---

pre_commit/languages/docker.py
tests/languages/docker_test.py

handle `SecurityOptions: null` in docker response
